Repository vuejs/core, pull requests merged in 2019-10, with the labels that each got.

#84 Fix grammar and spelling in build.js
  scripts/build.js
Labels: comment or text update, ready to merge

#88 fix: spelling mistake in ast.ts
  packages/compiler-core/src/ast.ts
Labels: comment or text update, ready to merge

#95 docs: fix 'commit message convention' link
  .github/contributing.md
  scripts/verifyCommit.js
Labels: comment or text update, ready to merge

#101 fix: simplify code in apiWatch.ts
  packages/runtime-core/src/apiWatch.ts
Labels: ready to merge

#118 fix(reactivity): Use unique symbol type for _isRef property of ref object
  packages/reactivity/__tests__/ref.spec.ts
  packages/reactivity/src/effect.ts
  packages/reactivity/src/ref.ts
Labels: ready to merge

#87 test: Add tests for some runtime helpers
  packages/runtime-core/__tests__/helpers/renderList.spec.ts
  packages/runtime-core/__tests__/helpers/toHandlers.spec.ts
  packages/runtime-test/src/jestUtils.ts
Labels: ready to merge

#126 fix: clean some unnecessary typing in reactivity
  packages/reactivity/src/computed.ts
  packages/reactivity/src/effect.ts
  packages/reactivity/src/reactive.ts
Labels: ready to merge

#129 fix(reactivity): explicitly do type conversions in template string
  packages/reactivity/__tests__/readonly.spec.ts
  packages/reactivity/src/baseHandlers.ts
Labels: ready to merge

#134 fix: rename param on function watch
  packages/runtime-core/src/apiWatch.ts
Labels: ready to merge

#122 chore: fix typo in rollup.config.js
  rollup.config.js
Labels: ready to merge

#124 feat: change _isRef to be access through the refSymbol
  packages/reactivity/src/computed.ts
  packages/reactivity/src/ref.ts
Labels: need guidance

#140 test(reactivity): fixed small copy & paste error
  packages/reactivity/__tests__/collections/WeakMap.spec.ts
  packages/reactivity/__tests__/collections/WeakSet.spec.ts
Labels: ready to merge

#119 test(runtime-core): createSlots method
  packages/runtime-core/__tests__/helpers/createSlots.spec.ts
  packages/runtime-core/src/helpers/createSlots.ts
Labels: ready to merge

#117 fix: wrong scope for event value
  packages/runtime-dom/src/modules/events.ts
Labels: need test

#162 chore(jest): ignore node_modules from watched files
  jest.config.js
Labels: ready to merge

#163 fix(compiler-core): use directive name in error code identifier
  packages/compiler-core/__tests__/transforms/transformSlotOutlet.spec.ts
  packages/compiler-core/__tests__/transforms/vFor.spec.ts
  packages/compiler-core/__tests__/transforms/vIf.spec.ts
  packages/compiler-core/__tests__/transforms/vSlot.spec.ts
  packages/compiler-core/src/errors.ts
  packages/compiler-core/src/transforms/transformElement.ts
  packages/compiler-core/src/transforms/transformSlotOutlet.ts
  packages/compiler-core/src/transforms/vFor.ts
  packages/compiler-core/src/transforms/vIf.ts
  packages/compiler-core/src/transforms/vSlot.ts
Labels: ready to merge

#155 refactor(reactivity): use function isSymbol instead of typeof
  packages/reactivity/src/baseHandlers.ts
Labels: ready to merge

#161 feat(computed): warn if trying to set a readonly computed
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/computed.ts
Labels: need guidance

#82 fix: add warnings
  packages/runtime-core/__tests__/apiOptions.spec.ts
  packages/runtime-core/__tests__/componentProxy.spec.ts
  packages/runtime-core/src/apiOptions.ts
  packages/runtime-core/src/componentProxy.ts
Labels: need test
