Repository vuejs/core, pull requests merged in 2021-02, with the labels that each got.

#2909 fix(runtime-core): ensure app instance can be garbage collected after unmount (close #2907)
  packages/runtime-core/src/apiCreateApp.ts
Labels: :cake: p2-nice-to-have, ready to merge

#2601 docs(type): remove unmount parameters
  packages/runtime-core/__tests__/apiCreateApp.spec.ts
  packages/runtime-core/src/apiCreateApp.ts
Labels: :cake: p2-nice-to-have, feat: types, ready to merge

#2943 fix: should prefix `ShadowRoot` with `window.`
  packages/runtime-dom/src/index.ts
Labels: :cake: p2-nice-to-have, ready to merge

#2868 docs(contributing): missing link to Scripts section
  .github/contributing.md
Labels: :broom: p1-chore, ready to merge

#2849 fix(runtime-dom): enable set form attr to null on form-elements (#2840)
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/patchProp.ts
  packages/shared/src/domTagConfig.ts
Labels: :hammer: p3-minor-bug, ready to merge

#3051 fix(compiler-sfc): the empty lang attribute should be treated as no lang specified
  packages/compiler-sfc/__tests__/parse.spec.ts
  packages/compiler-sfc/src/parse.ts
Labels: :cake: p2-nice-to-have, feat: compiler, ready to merge

#2857 fix: ensure all published packages contan a LICENCE file (close #2650)
  packages/compiler-sfc/LICENSE
  packages/compiler-ssr/LICENSE
  packages/shared/LICENSE
  packages/vue/LICENSE
Labels: :broom: p1-chore, ready to merge

#2930 fix(docs): change reference to passed deadline
  README.md
Labels: :broom: p1-chore, ready to merge

#2891 feat(runtime-core): props type support `BigInt`
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentProps.ts
Labels: ready to merge

#3005 fix(compiler-sfc): compiler blank srcset
  packages/compiler-sfc/__tests__/__snapshots__/templateTransformSrcset.spec.ts.snap
  packages/compiler-sfc/__tests__/templateTransformSrcset.spec.ts
  packages/compiler-sfc/src/templateTransformSrcset.ts
Labels: :beetle: bug, :exclamation: p4-important, feat: compiler, ready to merge

#2940 perf(reactivity): should not track `__isVue`
  packages/reactivity/src/baseHandlers.ts
Labels: feat: reactivity, ready to merge

#2900 feat(compiler-core): support `BigInt` in template
  packages/shared/src/globalsWhitelist.ts
  packages/vue/__tests__/index.spec.ts
Labels: ready to merge

#2976 chore: remove overloads numbers in comments
  packages/runtime-core/src/apiWatch.ts
Labels: :broom: p1-chore

#3136 types: focusin & out events
  packages/runtime-dom/types/jsx.d.ts
Labels: feat: types, ready to merge

#2710 feat(compiler-sfc): upgrade to postcss 8
  packages/compiler-sfc/package.json
  packages/compiler-sfc/src/compileStyle.ts
  packages/compiler-sfc/src/cssVars.ts
  packages/compiler-sfc/src/stylePluginScoped.ts
  packages/compiler-sfc/src/stylePluginTrim.ts
  yarn.lock
Labels: :broom: p1-chore, ready to merge

#3083 fix: remove superfluous spaces when normalizing class
  packages/shared/__tests__/normalizeProp.spec.ts
  packages/shared/src/normalizeProp.ts
Labels: ready to merge

#3074 fix(runtime-core): component methods should override global properties in DEV
  packages/runtime-core/__tests__/apiOptions.spec.ts
  packages/runtime-core/src/componentOptions.ts
Labels: ready to merge

#2750 fix(runtime-core): check the DEV_ROOT_FRAGMENT flag correctly in the dev environment
  packages/runtime-core/src/componentRenderUtils.ts
Labels: :exclamation: p4-important, ready to merge

#2974 types: use non-null assertion instead of explicit type cast
  packages/runtime-core/__tests__/apiInject.spec.ts
Labels: :broom: p1-chore, ready to merge

#3105 fix(runtime-core): allow overriding properties other than props
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: ready to merge

#3158 fix(runtime-core): align $parent/$root with the template ref when using expose
  packages/runtime-core/__tests__/apiExpose.spec.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: ready to merge

#3185 fix(compiler-dom): ensure global build filename matches the one defined in package.json (close #3181)
  packages/compiler-dom/package.json
Labels: :hammer: p3-minor-bug

#3170 feat: remove useless option in KeepAlive
  packages/runtime-core/src/components/KeepAlive.ts
Labels: :broom: p1-chore, ready to merge

#2753 fix(runtime-core): instanceWatch should pass `this.proxy` to source as the first argument
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :beetle: bug, :hammer: p3-minor-bug

#2729 fix(compiler-sfc): removeSpecifier issue when removing initial imports (script-setup)
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: :beetle: bug, :exclamation: p4-important

#2888 fix(runtime-dom): ensure readonly type prop on textarea is handled patched as attribute (close #2766)
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/patchProp.ts
Labels: :hammer: p3-minor-bug

#2945 feat(runtime-dom): add a warning for isCustomElement in runtime-only build
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/index.ts
  packages/runtime-dom/src/index.ts
Labels: :cake: p2-nice-to-have

#3165 types: support object as props type
  packages/runtime-core/src/componentProps.ts
  test-dts/component.test-d.ts
Labels: feat: types

#3184 fix(scheduler): should insert jobs in ascending order of job's id when flushing
  packages/runtime-core/__tests__/scheduler.spec.ts
  packages/runtime-core/src/scheduler.ts
Labels: :hammer: p3-minor-bug, need guidance

#3269 fix(compiler-ssr) ensure that ssrHelpers are unique after merge from parent context
  packages/compiler-ssr/__tests__/ssrElement.spec.ts
  packages/compiler-ssr/src/ssrCodegenTransform.ts
Labels: :exclamation: p4-important, feat: ssr
