Repository vuejs/core, pull requests merged in 2021-03, with the labels that each got.

#2929 fix(runtime-dom): support mounting app to svg container
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-dom/__tests__/createApp.spec.ts
  packages/runtime-dom/src/index.ts
Labels: :hammer: p3-minor-bug, need guidance

#2947 fix(types): allow style to be an array in JSX
  packages/runtime-dom/types/jsx.d.ts
Labels: feat: types, ready to merge, 🔍 review needed

#3191 fix(runtime-core): the forwarded template ref should be set correctly
  packages/runtime-core/__tests__/apiAsyncComponent.spec.ts
  packages/runtime-core/src/renderer.ts
Labels: :exclamation: p4-important, 🔍 review needed

#3308 fix(compiler-sfc): scope Id should not be attached to the Rules in the keyframes
  packages/compiler-sfc/__tests__/compileStyle.spec.ts
  packages/compiler-sfc/src/stylePluginScoped.ts
Labels: :exclamation: p4-important

#3353 fix(compiler-core): fix the detection of forwarded slots
  packages/compiler-core/__tests__/transforms/vSlot.spec.ts
  packages/compiler-core/src/transforms/vSlot.ts
Labels: :exclamation: p4-important, feat: compiler, feat: slots

#3259 fix(KeepAlive): adapt keepalive to ssr
  packages/runtime-core/src/components/KeepAlive.ts
  packages/server-renderer/__tests__/render.spec.ts
Labels: :exclamation: p4-important, feat: ssr

#3109 fix(transition): toggling branches with in-out mode should be transitioned correctly
  packages/runtime-core/__tests__/components/BaseTransition.spec.ts
  packages/runtime-core/src/components/BaseTransition.ts
Labels: :exclamation: p4-important, feat: transition

#3312 chore: add display name for suspense component
  packages/runtime-core/src/components/Suspense.ts
Labels: :broom: p1-chore, ready to merge

#2870 fix(teleport): targetAnchor should also be removed when unmounted
  packages/runtime-core/__tests__/components/Teleport.spec.ts
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-core/src/renderer.ts
Labels: :hammer: p3-minor-bug, feat: teleport

#3129 fix(runtime-core): handle error in async watchEffect
  packages/runtime-core/__tests__/errorHandling.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :hammer: p3-minor-bug

#3080 fix(rumtime-core): custom dom props should be cloned when cloning a hoisted DOM
  packages/runtime-dom/__tests__/nodeOps.spec.ts
  packages/runtime-dom/src/nodeOps.ts
Labels: :exclamation: p4-important

#3006 fix(server-renderer): respect the mixed render function in ssr
  packages/runtime-core/src/component.ts
  packages/server-renderer/__tests__/render.spec.ts
  packages/server-renderer/src/render.ts
Labels: :exclamation: p4-important, feat: ssr, 🔍 review needed

#3157 fix(Teleport): component with multi roots should be removed when unmounted
  packages/runtime-core/__tests__/components/Teleport.spec.ts
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-core/src/renderer.ts
Labels: :exclamation: p4-important, feat: teleport, 🔍 review needed, 🛑 on hold

#3406 fix(scheduler): ensure only skip unflushed job
  packages/runtime-core/src/scheduler.ts
Labels: :exclamation: p4-important

#3323 fix(ssr): watchEffect onInvalidate runner initialization (close #3322)
  packages/runtime-core/src/apiWatch.ts
  packages/server-renderer/__tests__/render.spec.ts
Labels: :exclamation: p4-important, feat: ssr

#3119 fix(types): union function prop
  packages/runtime-core/src/componentProps.ts
  test-dts/defineComponent.test-d.tsx
  test-dts/index.d.ts
Labels: feat: types

#2785 fix(compiler-core): should add the DEV_ROOT_FRAGMENT flag to v-if branchs
  packages/compiler-core/__tests__/__snapshots__/compile.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/vIf.spec.ts.snap
  packages/compiler-core/src/transforms/vIf.ts
Labels: :hammer: p3-minor-bug

#3299 fix(runtime-core): should not set the access cache in the data-fn
  packages/runtime-core/__tests__/rendererComponent.spec.ts
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: :hammer: p3-minor-bug

#3482 fix(compiler-core): should not condense whitespace in RCDATA text mode
  packages/compiler-core/__tests__/parse.spec.ts
  packages/compiler-core/src/parse.ts
Labels: :exclamation: p4-important, feat: compiler

#3477 fix: stringifyStatic should remove attribute with `null` value
  packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
  packages/compiler-dom/src/transforms/stringifyStatic.ts
Labels: :hammer: p3-minor-bug, feat: compiler

#3449 fix(compiler-sfc): should not rewrite scope variable
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: :hammer: p3-minor-bug

#3363 fix(runtime-core): fix warning for absent props
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentProps.ts
Labels: :hammer: p3-minor-bug

#3040 fix(runtime-core): should call hooks from chained mixins and extends
  packages/runtime-core/__tests__/apiOptions.spec.ts
  packages/runtime-core/src/componentOptions.ts
Labels: :hammer: p3-minor-bug

#3202 fix(runtime-core): the select tag's multiple prop should be set before the children mounting
  packages/runtime-core/src/renderer.ts
  packages/runtime-dom/__tests__/nodeOps.spec.ts
  packages/runtime-dom/src/nodeOps.ts
Labels: :hammer: p3-minor-bug

#2938 fix(compiler-core): avoid generating useless createVNode helper
  packages/compiler-core/__tests__/__snapshots__/compile.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/hoistStatic.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/transformExpressions.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/vFor.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/vIf.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/vModel.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/vOnce.spec.ts.snap
  packages/compiler-core/__tests__/transforms/__snapshots__/vSlot.spec.ts.snap
  packages/compiler-core/src/transform.ts
  packages/compiler-core/src/transforms/hoistStatic.ts
  packages/compiler-core/src/transforms/vFor.ts
  packages/compiler-core/src/transforms/vIf.ts
  packages/compiler-dom/__tests__/transforms/__snapshots__/vModel.spec.ts.snap
  packages/compiler-dom/__tests__/transforms/__snapshots__/vShow.spec.ts.snap
  packages/compiler-sfc/__tests__/__snapshots__/templateTransformAssetUrl.spec.ts.snap
  packages/compiler-ssr/__tests__/ssrComponent.spec.ts
  packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
Labels: :hammer: p3-minor-bug, feat: compiler

#3443 fix(compiler-core): allow unicode to appear in identifiers
  packages/compiler-core/__tests__/transforms/vModel.spec.ts
  packages/compiler-core/src/utils.ts
Labels: :hammer: p3-minor-bug, feat: compiler

#3474 fix(runtime-core): cache the value returned from the default factory to avoid unnecessary watcher trigger
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/componentProps.ts
Labels: :hammer: p3-minor-bug

#3319 types: the data type of the public instance should be unwrapped
  packages/reactivity/src/index.ts
  packages/reactivity/src/reactive.ts
  packages/runtime-core/src/componentPublicInstance.ts
  test-dts/defineComponent.test-d.tsx
Labels: :hammer: p3-minor-bug, feat: types, ready to merge

#3246 fix(hydration): vnode is of Text type and with empty text should be skipped when hydrateChildren
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: :hammer: p3-minor-bug

#3247 fix(hydration): should handle camel-case name when performing match assertion
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: :hammer: p3-minor-bug

#3311 fix(Teleport): fallback to non-optimized mode when HRM performing updates
  packages/runtime-core/__tests__/hmr.spec.ts
  packages/runtime-core/src/components/Teleport.ts
Labels: :hammer: p3-minor-bug, feat: hmr, feat: teleport

#3003 fix(reactivity): support shallow readonly for collections
  packages/reactivity/__tests__/collections/shallowReadonly.spec.ts
  packages/reactivity/__tests__/readonly.spec.ts
  packages/reactivity/__tests__/shallowReadonly.spec.ts
  packages/reactivity/src/collectionHandlers.ts
  packages/reactivity/src/reactive.ts
Labels: :hammer: p3-minor-bug, feat: reactivity

#2851 fix(reactivity): ensure that shallow and normal proxies are tracked seperately (close #2843)
  packages/reactivity/__tests__/shallowReactive.spec.ts
  packages/reactivity/__tests__/shallowReadonly.spec.ts
  packages/reactivity/src/baseHandlers.ts
  packages/reactivity/src/reactive.ts
Labels: :hammer: p3-minor-bug, need guidance

#3499 fix(runtime-core): avoid unmount teleport's children multiple times
  packages/runtime-core/__tests__/components/Teleport.spec.ts
  packages/runtime-core/src/renderer.ts
Labels: :hammer: p3-minor-bug

#3171 fix(jsx): JSX.Element extends VNode
  packages/runtime-core/src/h.ts
  packages/runtime-dom/types/jsx.d.ts
  test-dts/functionalComponent.test-d.tsx
  test-dts/tsx.test-d.tsx
Labels: :hammer: p3-minor-bug, need guidance

#2904 fix(baseHandlers): trigger will called two times when set the same proxy value
  packages/reactivity/__tests__/effect.spec.ts
  packages/reactivity/src/baseHandlers.ts
Labels: :hammer: p3-minor-bug, feat: reactivity

#3481 fix(types): add a type-only differentiator to assist Mixin's type infer
  packages/runtime-core/src/componentOptions.ts
  test-dts/defineComponent.test-d.tsx
Labels: :hammer: p3-minor-bug, feat: types

#2927 fix(transformElement): properly transform replaced nodes
  packages/compiler-core/__tests__/transforms/transformElement.spec.ts
  packages/compiler-core/src/transforms/transformElement.ts
Labels: :hammer: p3-minor-bug

#3132 Fix missing whitespace issue in srcsets
  packages/compiler-sfc/__tests__/__snapshots__/templateTransformSrcset.spec.ts.snap
  packages/compiler-sfc/src/templateTransformSrcset.ts
Labels: :exclamation: p4-important, feat: sfc

#3501 fix(runtime-dom): fix the event listeners call in firefox <= 53
  packages/runtime-dom/src/modules/events.ts
Labels: :exclamation: p4-important

#3206 perf(runtime-core): optimize the performance of `getTypeIndex`
  packages/runtime-core/src/componentProps.ts
Labels: :cake: p2-nice-to-have
