Repository vuejs/core, pull requests merged in 2021-05, with the labels that each got.

#3066 fix(runtime-core): watching multiple sources: computed
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :cake: p2-nice-to-have, feat: reactivity, 🔍 review needed

#3642 fix(Teleport): avoid changing the reference of vnode.dynamicChildren
  packages/runtime-core/src/components/Teleport.ts
Labels: :hammer: p3-minor-bug, feat: hmr

#3563 fix(hydration): refactor async component hydration
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
  packages/runtime-core/src/renderer.ts
Labels: :exclamation: p4-important

#3604 fix(reactivity): fix the tracking when readonly + reactive is used for Map
  packages/reactivity/__tests__/effect.spec.ts
  packages/reactivity/src/collectionHandlers.ts
Labels: :exclamation: p4-important, feat: reactivity

#3757 fix(compiler-core): bail out to array children when the element has custom directives + only one text child node
  packages/compiler-core/__tests__/transforms/__snapshots__/transformText.spec.ts.snap
  packages/compiler-core/__tests__/transforms/transformText.spec.ts
  packages/compiler-core/src/transforms/transformText.ts
Labels: :exclamation: p4-important, feat: compiler

#3726 fix(types): declared prop keys should always exist in `props` argument
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/helpers/typeUtils.ts
  test-dts/component.test-d.ts
Labels: :beetle: bug, feat: types

#3767 fix(compiler-core): fix the whitespace management of component slots
  packages/compiler-core/__tests__/transforms/__snapshots__/vSlot.spec.ts.snap
  packages/compiler-core/__tests__/transforms/vSlot.spec.ts
  packages/compiler-core/src/transforms/vSlot.ts
Labels: :exclamation: p4-important

#3783 types(props): Support `undefined` as default
  packages/runtime-core/src/componentProps.ts
  test-dts/defineComponent.test-d.tsx
Labels: :cake: p2-nice-to-have, feat: types

#3776 types(jsx): improve type for number attributes
  packages/runtime-dom/types/jsx.d.ts
Labels: feat: types

#2548 fix(types/reactivity): error TS4058 caused by `RefSymbol`
  packages/reactivity/src/ref.ts
Labels: :exclamation: p4-important, feat: types

#3622 fix(compiler-dom): comments in the v-if branchs should be ignored when used in Transition
  packages/compiler-core/src/transforms/vIf.ts
  packages/compiler-dom/__tests__/transforms/__snapshots__/warnTransitionChildren.spec.ts.snap
  packages/compiler-dom/__tests__/transforms/warnTransitionChildren.spec.ts
Labels: :exclamation: p4-important

#3698 fix(runtime-core): avoid the proxy object polluting the slots of the internal instance
  packages/runtime-core/src/componentRenderContext.ts
  packages/runtime-core/src/componentSlots.ts
Labels: :exclamation: p4-important

#3531 fix(KeepAlive): should work with async component
  packages/runtime-core/__tests__/components/KeepAlive.spec.ts
  packages/runtime-core/src/apiAsyncComponent.ts
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: :exclamation: p4-important

#3554 fix(runtime-core): should not track dynamic children when the user calls a compiled slot inside template expression
  packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
  packages/runtime-core/src/compat/instance.ts
  packages/runtime-core/src/compat/renderFn.ts
  packages/runtime-core/src/componentRenderContext.ts
  packages/runtime-core/src/componentSlots.ts
  packages/runtime-core/src/helpers/renderSlot.ts
  packages/runtime-core/src/vnode.ts
Labels: :exclamation: p4-important

#3629 fix(runtime-core): ensure the nested teleport can be unmounted correctly
  packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
  packages/runtime-core/src/components/Teleport.ts
Labels: :exclamation: p4-important

#3781 fix(runtime-core): treat slots manually written by the user as dynamic
  packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
  packages/runtime-core/src/vnode.ts
Labels: :exclamation: p4-important

#3699 fix(runtime-core): should disable tracking inside directive lifecycle hooks
  packages/runtime-core/__tests__/directives.spec.ts
  packages/runtime-core/src/directives.ts
Labels: :hammer: p3-minor-bug

#3670 fix(runtime-core): the component VNode should be cloned when reusing it
  packages/runtime-core/__tests__/rendererComponent.spec.ts
  packages/runtime-core/src/vnode.ts
Labels: :hammer: p3-minor-bug

#3564 fix(runtime-dom): should remove attribute when binding `null` to `value`
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/modules/props.ts
Labels: :hammer: p3-minor-bug

#3582 fix(compiler-sfc): correctly remove parens used for wrapping
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: :hammer: p3-minor-bug

#3626 fix(compiler-sfc): template assignment expression codegen correctly
  packages/compiler-core/src/transforms/transformExpression.ts
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
Labels: :hammer: p3-minor-bug, feat: sfc
