Repository vuejs/core, pull requests merged in 2021-07, with the labels that each got.

#3656 feat(types): support renaming for props
  packages/runtime-core/src/componentProps.ts
Labels: feat: types

#3570 feat(types): support find definition for jsx tags, events
  packages/runtime-dom/types/jsx.d.ts
Labels: feat: types

#2195 feat(reactivity): new effectScope API
  packages/reactivity/__tests__/effectScope.spec.ts
  packages/reactivity/src/effect.ts
  packages/reactivity/src/effectScope.ts
  packages/reactivity/src/index.ts
  packages/reactivity/src/warning.ts
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiComputed.ts
  packages/runtime-core/src/apiLifecycle.ts
  packages/runtime-core/src/apiSetupHelpers.ts
  packages/runtime-core/src/apiWatch.ts
  packages/runtime-core/src/compat/global.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/componentProps.ts
  packages/runtime-core/src/index.ts
  packages/runtime-core/src/renderer.ts
Labels: :cake: p2-nice-to-have, planned: 3.2

#4017 feat(reactivity): bitwise dep markers to optimize re-tracking
  packages/reactivity/__tests__/effect.spec.ts
  packages/reactivity/src/Dep.ts
  packages/reactivity/src/computed.ts
  packages/reactivity/src/effect.ts
  packages/reactivity/src/ref.ts
  packages/runtime-core/src/renderer.ts
Labels: :exclamation: p4-important, planned: 3.2

#3578 fix(runtime-dom): capture errors when setting value for IDL
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/modules/props.ts
Labels: :cake: p2-nice-to-have

#2802 fix(compiler-sfc): duplicated injected css var with repeated vars
  packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap
  packages/compiler-sfc/__tests__/cssVars.spec.ts
  packages/compiler-sfc/src/cssVars.ts
Labels: :cake: p2-nice-to-have, feat: sfc

#4141 refactor(types): improve of type assertion
  packages/compiler-core/src/ast.ts
  packages/compiler-core/src/errors.ts
Labels: feat: types

#3520 feat(compiler-sfc): ignore empty blocks
  packages/compiler-sfc/__tests__/parse.spec.ts
  packages/compiler-sfc/src/parse.ts
Labels: feat: sfc

#4176 docs: use vite as a startup tool
  README.md
Labels: :broom: p1-chore

#4162 types(reactivity): Simplify the SymbolExtract
  packages/reactivity/__tests__/ref.spec.ts
  packages/reactivity/src/ref.ts
  test-dts/ref.test-d.ts
Labels: feat: types

#4194 types(reactivity): simplify the UnwrapNestedRefs
  packages/reactivity/src/reactive.ts
  packages/reactivity/src/ref.ts
Labels: feat: types
