Repository vuejs/core, pull requests merged in 2021-04, with the labels that each got.

#2590 chore(shared): use type `NormalizedStyle`
  packages/shared/src/normalizeProp.ts
Labels: :broom: p1-chore

#3523 fix(runtime-core): make manually written render function work with optimized slots
  packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
  packages/runtime-core/src/componentSlots.ts
  packages/runtime-core/src/renderer.ts
Labels: :hammer: p3-minor-bug

#3409 chore(runtime-core): change the position of the mountChildren parameter
  packages/runtime-core/src/renderer.ts
Labels: :cake: p2-nice-to-have
