Repository vuejs/core, pull requests merged in 2021-08, with the labels that each got.

#4242 updated typing of key in VNodeProps (fix #4240)
  packages/runtime-core/src/components/KeepAlive.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-core/src/vnode.ts
Labels: feat: types

#4249 docs(server-renderer) fix typo in `renderToWebStream` error, and remove Cloudflare Worker reference
  packages/server-renderer/README.md
  packages/server-renderer/src/renderToStream.ts
Labels: :broom: p1-chore

#4258 chore(test-dts): rename regSugar.test-d.ts to refSugar.test-d.ts
  test-dts/refSugar.test-d.ts
Labels: ready to merge, :broom: p1-chore

#4239 test(reactivity): add test case for effectScope
  packages/reactivity/__tests__/effectScope.spec.ts
  packages/reactivity/src/effectScope.ts
Labels: :broom: p1-chore

#4302 types(runtime-core): improve forceUpdate type
  packages/runtime-core/src/componentPublicInstance.ts
Labels: feat: types

#2486 fix(types): fix the jsx type of ref function
  packages/runtime-dom/types/jsx.d.ts
Labels: feat: types

#4359 chore: missing space in warn
  packages/reactivity/src/collectionHandlers.ts
Labels: :broom: p1-chore

#4421 test(reactivity): delete unnecessary async in tests
  packages/reactivity/__tests__/shallowReactive.spec.ts
  packages/reactivity/__tests__/shallowReadonly.spec.ts
Labels: :broom: p1-chore

#4405 types(PropType): Allow `undefined` function to be used on `PropType`
  packages/runtime-core/src/componentProps.ts
  test-dts/defineComponent.test-d.tsx
Labels: feat: types
