Repository vuejs/core, pull requests merged in 2021-09, with the labels that each got.

#4434 chore: fix typo in error message
  packages/compiler-core/src/errors.ts
Labels: :broom: p1-chore

#4459 refactor(compiler): refine CDATA endTokens
  packages/compiler-core/src/parse.ts
Labels: :broom: p1-chore

#4407 types(reactivity): delete didn't used export.
  packages/reactivity/src/index.ts
  packages/reactivity/src/ref.ts
  packages/runtime-core/src/index.ts
Labels: :broom: p1-chore

#4490 test(reactivity): remove useless 'async'
  packages/reactivity/__tests__/effectScope.spec.ts
Labels: :broom: p1-chore

#4458 fix(compiler-sfc): support nested await statements
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: feat: script-setup

#4631 fix(server-renderer): respect compilerOptions during runtime template compilation
  packages/server-renderer/__tests__/ssrCompilerOptions.spec.ts
  packages/server-renderer/src/helpers/ssrCompile.ts
Labels: feat: ssr
