Repository vuejs/core, pull requests merged in 2022-11, with the labels that each got.

#6182 fix(runtime-dom): ensure customElement handles empty props correctly. (fix #6361,#6895)
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: :exclamation: p4-important, feat: custom elements

#6303 fix(reactivity-transform): add semicolon after statements
  packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap
  packages/compiler-sfc/src/compileScript.ts
  packages/reactivity-transform/__tests__/__snapshots__/reactivityTransform.spec.ts.snap
  packages/reactivity-transform/src/reactivityTransform.ts
Labels: ready to merge, :hammer: p3-minor-bug

#6636 fix(normalizaProp): support css variable as number
  packages/server-renderer/__tests__/ssrRenderAttrs.spec.ts
  packages/shared/src/domAttrConfig.ts
  packages/shared/src/normalizeProp.ts
Labels: ready to merge, :hammer: p3-minor-bug

#6769 fix(compiler-core): function expression support arrow function type in typescript
  packages/compiler-core/__tests__/transforms/vOn.spec.ts
  packages/compiler-core/src/transforms/vOn.ts
Labels: ready to merge

#6778 fix(sfc-compiler): fix duplicated declarations of macros
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: ready to merge

#6777 fix(shared): parse multi-line inline style
  packages/shared/__tests__/normalizeProp.spec.ts
  packages/shared/src/normalizeProp.ts
Labels: ready to merge, :hammer: p3-minor-bug

#6808 fix(compiler-sfc): ignore style comment in `transform` stage
  packages/compiler-sfc/__tests__/compileTemplate.spec.ts
  packages/shared/src/normalizeProp.ts
Labels: ready to merge

#6809 fix(runtime-core): keep-alive exclude component in hmrDirtyComponents…
  packages/runtime-core/src/components/KeepAlive.ts
Labels: ready to merge

#6828 fix(compiler-core): keep whitespaces with newline between interpolation and comment
  packages/compiler-core/__tests__/parse.spec.ts
  packages/compiler-core/src/parse.ts
Labels: :hammer: p3-minor-bug

#6855 fix: stricter type condition for `EventHandlers`
  packages/runtime-dom/types/jsx.d.ts
Labels: ready to merge, feat: types

#7075 fix(watch): for immediate watch with single source, ensure cb is called with undefined as oldValue (fix: #7074)
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :exclamation: p4-important, regression

#5098 fix(runtime-dom): Ensure custom Elements can inherit provides from ancestors (fix: #5096)
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: :hammer: p3-minor-bug, feat: custom elements

#5378 fix(runtime-core): custom-element: ensure event names are hyphenated (fix: #5373)
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: :hammer: p3-minor-bug, 🔍 review needed, feat: custom elements

#5601 fix(define-custom-element): ensure async wrapper passes custom element callback to inner component This ensures event emits work for async coponent in custom elements. (fix #5599)
  packages/runtime-core/src/apiAsyncComponent.ts
  packages/runtime-core/src/hmr.ts
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: need guidance, :hammer: p3-minor-bug, feat: custom elements

#5328 fix(runtime-core: ensure customElements have set domprop listeners synchronously if possible.
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: :hammer: p3-minor-bug, 🔍 review needed, feat: custom elements

#7112 fix(compiler-sfc): never skip Function prop type
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: :hammer: p3-minor-bug

#3969 types(runtime-core): enable plugin option types
  packages/runtime-core/src/apiCreateApp.ts
  test-dts/appUse.test-d.ts
Labels: feat: types

#6774 refactor(compiler-core): make ast.helpers a Set
  packages/compiler-core/__tests__/__snapshots__/parse.spec.ts.snap
  packages/compiler-core/__tests__/codegen.spec.ts
  packages/compiler-core/src/ast.ts
  packages/compiler-core/src/codegen.ts
  packages/compiler-core/src/transform.ts
  packages/compiler-sfc/src/compileScript.ts
  packages/compiler-ssr/__tests__/ssrInjectCssVars.spec.ts
  packages/compiler-ssr/src/ssrCodegenTransform.ts
Labels: ready to merge

#6948 Exchange the order of `setScopeId` and `props initiate`
  packages/runtime-core/__tests__/scopeId.spec.ts
  packages/runtime-core/src/renderer.ts
Labels: ready to merge

#7037 chore: comment and order keywords in list alphabetically
  packages/compiler-core/src/validateExpression.ts
Labels: :broom: p1-chore
