Repository vuejs/core, pull requests merged in 2022-05, with the labels that each got.

#3791 types(markRaw): keep the original type when unwrapping `markRaw`
  packages/reactivity/src/reactive.ts
  packages/reactivity/src/ref.ts
  test-dts/index.d.ts
  test-dts/reactivity.test-d.ts
Labels: feat: types, :hammer: p3-minor-bug

#2682 chore: reference to transformExpressions
  packages/compiler-dom/src/transforms/stringifyStatic.ts
Labels: :broom: p1-chore

#2890 chore(server renderer): readable warn message
  packages/server-renderer/src/render.ts
Labels: :broom: p1-chore

#2923 types(compiler-sfc): export SFCParseResult type
  packages/compiler-sfc/src/index.ts
Labels: feat: sfc, :broom: p1-chore

#3217 chore(runtime-core): use `getGlobalThis`
  packages/runtime-core/src/hmr.ts
Labels: :broom: p1-chore

#3700 chore(runtime-core): remove duplicate assignment
  packages/runtime-core/src/renderer.ts
Labels: :broom: p1-chore

#5358 fix(runtime-core): Ensure raw Slots are only normalized once by withContext (Fix: #5353)
  packages/runtime-core/src/componentSlots.ts
Labels: feat: slots, :hammer: p3-minor-bug

#5135 fix(ssr): don't warn for missing teleport target if disabled
  packages/server-renderer/src/render.ts
Labels: feat: teleport, :hammer: p3-minor-bug

#5177 fix(runtime-core): transition hooks can be arrays of functions
  packages/runtime-core/src/components/BaseTransition.ts
Labels: feat: transition, :hammer: p3-minor-bug

#3473 fix(types): allow indeterminate for checkbox
  packages/runtime-dom/types/jsx.d.ts
Labels: :cake: p2-nice-to-have

#5459 fix(runtime-core): AsyncComponent work with KeepAlive
  packages/runtime-core/__tests__/apiAsyncComponent.spec.ts
  packages/runtime-core/src/apiAsyncComponent.ts
Labels: feat: keep-alive, :exclamation: p4-important

#5404 fix(compiler-sfc): fix checkInvalidScopeReference method error
  packages/compiler-sfc/src/compileScript.ts
Labels: feat: sfc

#5436 fix(compiler-sfc): sfc props transform aliasing w/ StringLiteral
  packages/compiler-core/src/transforms/transformExpression.ts
  packages/compiler-sfc/__tests__/__snapshots__/compileScriptPropsTransform.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts
  packages/compiler-sfc/src/compileScript.ts
  packages/reactivity-transform/src/reactivityTransform.ts
  packages/shared/src/index.ts
Labels: feat: sfc

#5187 fix(ssr): render teleport inside async component
  packages/server-renderer/__tests__/ssrTeleport.spec.ts
  packages/server-renderer/src/renderToString.ts
Labels: feat: teleport, feat: ssr, :hammer: p3-minor-bug

#3265 refactor(runtime-core): extract function `isReservedPrefix`
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: :cake: p2-nice-to-have

#5968 types: Spreading `$props` causes typescript error
  packages/runtime-core/src/index.ts
  packages/runtime-core/src/vnode.ts
  packages/runtime-dom/types/jsx.d.ts
  test-dts/componentTypeExtensions.test-d.tsx
  test-dts/defineComponent.test-d.tsx
Labels: feat: types
