Repository vuejs/core, pull requests merged in 2022-01, with the labels that each got.

#5260 fix(KeepAlive): remove cached VNode properly
  packages/runtime-core/src/components/KeepAlive.ts
Labels: need test

#3559 docs(contributing): missing structure info for compiler-sfc
  .github/contributing.md
Labels: feat: sfc

#5228 fix(compat): ensure fallthrough *Native events are not dropped during props update (fix #5222)
  packages/runtime-core/src/componentProps.ts
Labels: need guidance, :hammer: p3-minor-bug, feat: v2 compat

#5291 fix(compiler-core): handle v-memo in template v-for
  packages/compiler-core/__tests__/transforms/__snapshots__/vMemo.spec.ts.snap
  packages/compiler-core/src/transforms/vFor.ts
Labels: ready to merge, :hammer: p3-minor-bug

#5048 fix(reactivity): mutating a readonly ref nested in a reactive object should fail. (close #5042)
  packages/reactivity/__tests__/readonly.spec.ts
  packages/reactivity/src/baseHandlers.ts
Labels: need guidance

#5212 fix(types): calling readonly() with ref() should return Readonly<Ref<T>>
  packages/reactivity/__tests__/readonly.spec.ts
  packages/reactivity/src/reactive.ts
  test-dts/ref.test-d.ts
Labels: :lady_beetle: bug, feat: types
