Repository vuejs/core, pull requests merged in 2022-04, with the labels that each got.

#5517 fix(runtime-core): fix event listener as dynamicProp is added erroneously to props
  packages/runtime-core/src/componentProps.ts
Labels: :exclamation: p4-important

#4840 fix(runtime-core): Avoid mutating original options object in createApp (fix #4398)
  packages/runtime-core/__tests__/helpers/resolveAssets.spec.ts
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-dom/__tests__/createApp.spec.ts
Labels: ready to merge, 🔩 p2-edge-case

#5022 fix(runtime-core): ensure that binding.instance in custom directive hooks properly exposes properties on closed instances (fix: #5018)
  packages/runtime-core/__tests__/directives.spec.ts
  packages/runtime-core/src/directives.ts
Labels: :exclamation: p4-important, feat: script-setup

#5485 fix: patch translate as an attr
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/patchProp.ts
Labels: ready to merge, :hammer: p3-minor-bug

#5548 chore(reactivity):use warn
  packages/reactivity/src/baseHandlers.ts
Labels: ready to merge, :broom: p1-chore

#5480 chore(@vue/shared): add `"sideEffects": false`
  packages/shared/package.json
Labels: :sparkles: enhancement

#5565 fix(suspense): warn when using asnyc setup when not inside a Supsense boundary. (fix: #3659)
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/component.ts
Labels: feat: suspense, :hammer: p3-minor-bug

#4657 fix(custom-elements): work with async component + slots
  packages/runtime-core/src/helpers/renderSlot.ts
  packages/runtime-dom/__tests__/customElement.spec.ts
Labels: ready to merge, :hammer: p3-minor-bug, feat: custom elements

#5348 fix(runtime-dom): properly handle custom style properties with falsy values (fix: #5322)
  packages/runtime-dom/__tests__/patchStyle.spec.ts
  packages/runtime-dom/src/modules/style.ts
Labels: :hammer: p3-minor-bug

#5564 Fix: missing reserved props `ref_key` & `ref_for` (fix #5563)
  packages/server-renderer/__tests__/ssrRenderAttrs.spec.ts
  packages/server-renderer/src/helpers/ssrRenderAttrs.ts
Labels: feat: ssr, :hammer: p3-minor-bug

#5498 fix(compiler-sfc): Check if the type modifier in the import statement
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: feat: compiler, :hammer: p3-minor-bug

#5679 fix(runtime-core): ensure custom events are not emitted anymore after unmount. (fix #5674)
  packages/runtime-core/__tests__/componentEmits.spec.ts
  packages/runtime-core/src/componentEmits.ts
Labels: :hammer: p3-minor-bug
