Repository vuejs/core, pull requests merged in 2022-10, with the labels that each got.

#2614 types: creating Teleport with h and RawSlots #2613
  packages/runtime-core/src/h.ts
  test-dts/h.test-d.ts
Labels: ready to merge, feat: teleport

#5670 fix(runtime-core): ensure that errors in slot function execution do not affect block tracking (fix #5657)
  packages/runtime-core/__tests__/vnode.spec.ts
  packages/runtime-core/src/componentRenderContext.ts
Labels: ready to merge, :exclamation: p4-important

#5458 fix(types): ensure createBlock() helper accepts Teleport and Supsense types (fix: #2855)
  packages/runtime-core/src/vnode.ts
  test-dts/compiler.test-d.ts
Labels: ready to merge, feat: types, :hammer: p3-minor-bug

#6810 fix(reactivity): enable trigger when use str to set length of arr
  packages/reactivity/__tests__/effect.spec.ts
  packages/reactivity/src/effect.ts
Labels: ready to merge

#6916 fix(runtime-core): ensure props definition objects are not mutated during props normalization (close: #6915)
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentProps.ts
Labels: ready to merge

#5377 fix(runtime-core): custom-element: ensure number casting of camelCase props. (fix: #5374)
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: :hammer: p3-minor-bug, feat: custom elements

#3219 types(h): Support passing `props` to `Component` when using `h`
  packages/runtime-core/src/h.ts
  test-dts/h.test-d.ts
Labels: feat: types

#3820 fix(types): should unwrap tuple correctly
  packages/reactivity/src/ref.ts
  test-dts/reactivity.test-d.ts
Labels: ready to merge, feat: types

#4512 feat(sfc): support using extends interface with defineProps()
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: feat: sfc, feat: script-setup

#5389 types(runtime-core): added `ComponentCustomProperties` type to `globalProperties`
  packages/runtime-core/src/apiCreateApp.ts
  test-dts/componentTypeExtensions.test-d.tsx
Labels: feat: types, :cake: p2-nice-to-have

#5394 fix(compiler-sfc): Optimize the value of emitIdentifier.
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: ready to merge

#6136 fix(types): `$watch` callback parameters type
  packages/runtime-core/src/componentPublicInstance.ts
  test-dts/watch.test-d.ts
Labels: ready to merge

#6138 fix(runtime-core): `in` operator returning `false` for built-in instance properties in `exposeProxy` (fix #6137)
  packages/runtime-core/__tests__/apiExpose.spec.ts
  packages/runtime-core/src/component.ts
Labels: ready to merge, 🔩 p2-edge-case

#6139 fix(watch): should work normal w/ sync flush in ssr
  packages/runtime-core/src/apiWatch.ts
  packages/server-renderer/__tests__/ssrWatch.spec.ts
  packages/server-renderer/src/render.ts
  packages/server-renderer/src/renderToStream.ts
  packages/server-renderer/src/renderToString.ts
Labels: :hammer: p3-minor-bug
