Repository vuejs/core, pull requests merged in 2023-10, with the labels that each got.

#9377 fix(compat): return value of vue compat set()
  packages/runtime-core/src/compat/instance.ts
Labels: ready to merge

#9438 chore: fix link in changelog [ci-skip]
  CHANGELOG.md
Labels: :broom: p1-chore

#8986 ci: use `.node-version` to maintain node version
  .github/workflows/canary.yml
  .github/workflows/ci.yml
  .github/workflows/size-data.yml
  .github/workflows/size-report.yml
  .node-version
Labels: ready to merge, scope: infra

#8956 fix(template-explorer): template-explorer highlighting
  packages/template-explorer/src/index.ts
Labels: ready to merge

#8752 feat: support space contained in the filename for asset
  packages/compiler-sfc/__tests__/templateTransformAssetUrl.spec.ts
  packages/compiler-sfc/src/template/transformAssetUrl.ts
Labels: ready to merge, :hammer: p3-minor-bug, need discussion

#7557 fix(compiler-ssr): TransitionGroup owns style-scoped properties on SSR
  packages/compiler-ssr/__tests__/ssrScopeId.spec.ts
  packages/compiler-ssr/src/transforms/ssrTransformTransitionGroup.ts
Labels: ready to merge, :exclamation: p4-important

#6484 fix(runtime-core): delete stale slots which are present but undefined
  packages/runtime-core/__tests__/componentSlots.spec.ts
  packages/runtime-core/src/componentSlots.ts
Labels: ready to merge, scope: slots, :exclamation: p4-important

#7341 fix(runtime-core): Fix cssvars reporting error when teleport is disabled
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts
Labels: ready to merge, scope: teleport, :hammer: p3-minor-bug, scope: sfc-style-vars

#6529 fix(teleport): ensure descendent component would be unmounted correctly
  packages/runtime-core/__tests__/components/Teleport.spec.ts
  packages/runtime-core/src/components/Teleport.ts
Labels: ready to merge, scope: teleport, :exclamation: p4-important

#8549 perf: replace Map/Set with WeakMap/WeakSet
  packages/compiler-core/src/transform.ts
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/compat/componentAsync.ts
  packages/runtime-core/src/compat/componentFunctional.ts
Labels: ready to merge

#8796 types: support contenteditable="plaintext-only"
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge, easy for merge

#8798 fix(compiler-sfc): unexpected model name conflict
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineModel.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineModel.spec.ts
  packages/compiler-sfc/src/script/context.ts
Labels: ready to merge, :hammer: p3-minor-bug, easy for merge

#9019 style: remove eslint-disable rules
  packages/compiler-dom/src/decodeHtmlBrowser.ts
  packages/dts-test/ref.test-d.ts
  packages/reactivity-transform/src/reactivityTransform.ts
  packages/reactivity/__tests__/collections/Map.spec.ts
  packages/reactivity/__tests__/collections/Set.spec.ts
  packages/runtime-core/src/compat/global.ts
Labels: ready to merge, :broom: p1-chore

#9442 fix(ssr): render initial selected properly
  packages/compiler-ssr/__tests__/ssrVModel.spec.ts
  packages/compiler-ssr/src/transforms/ssrVModel.ts
Labels: :fire: p5-urgent, regression

#9446 fix: correctly resolve types from relative paths on Windows
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: :lady_beetle: bug, :exclamation: p4-important, scope: script-setup

#7748 fix(runtime-core): ensure jobs are in the correct order
  packages/runtime-core/__tests__/scheduler.spec.ts
  packages/runtime-core/src/scheduler.ts
Labels: :exclamation: p4-important

#9399 fix(ssr): Using teleport disabled causes mismatch
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: scope: teleport, scope: ssr, :exclamation: p4-important, ready for review

#9443 chore: upgrade deps
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
Labels: ready to merge

#9388 fix(Suspense): mount runs too early when used in Transition
  packages/runtime-core/src/components/Suspense.ts
  packages/vue/__tests__/e2e/Transition.spec.ts
Labels: scope: transition, scope: suspense, :exclamation: p4-important

#5432 types(runtime-core): Add `h` overload to support string|Component|DefineComponent types
  packages/dts-test/h.test-d.ts
  packages/runtime-core/src/h.ts
Labels: ready to merge, scope: types, :hammer: p3-minor-bug

#8859 feat(ssr): transition appear work with SSR
  packages/compiler-ssr/__tests__/ssrTransition.spec.ts
  packages/compiler-ssr/src/transforms/ssrTransformComponent.ts
  packages/compiler-ssr/src/transforms/ssrTransformTransition.ts
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
  packages/runtime-core/src/renderer.ts
Labels: scope: transition, scope: ssr, :exclamation: p4-important, ready for review

#9468 types(ComponentPublicInstance): fix generated props to keep ComponentCustomProps
  packages/dts-built-test/README.md
  packages/dts-built-test/package.json
  packages/dts-built-test/src/index.ts
  packages/dts-test/built.test-d.ts
  packages/dts-test/package.json
  packages/runtime-core/src/componentPublicInstance.ts
  pnpm-lock.yaml
Labels: scope: types, :exclamation: p4-important

#8985 chore: use helper function for merging vitest config
  vitest.e2e.config.ts
  vitest.unit.config.ts
Labels: ready to merge

#8562 chore: remove unnecessary imports from vitest
  packages/runtime-core/__tests__/apiOptions.spec.ts
  packages/runtime-dom/__tests__/customizedBuiltIn.spec.ts
  packages/vue-compat/__tests__/global.spec.ts
  packages/vue-compat/__tests__/instance.spec.ts
  scripts/setupVitest.ts
Labels: ready to merge, :broom: p1-chore

#9306 chore: fix typo
  .github/contributing.md
Labels: ready to merge, :broom: p1-chore

#9043 types(runtime-dom): update aria-relevant type
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge, scope: types

#5955 fix(compile-sfc): Support define Error as prop type
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineProps.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: :cake: p2-nice-to-have, scope: script-setup

#9497 feat(reactivity): expose last result for computed getter
  packages/reactivity/src/computed.ts
Labels: scope: reactivity
