Repository vuejs/core, pull requests merged in 2023-07, with the labels that each got.

#7174 workflow: update pnpm verification script
  package.json
  scripts/preinstall.js
Labels: ready to merge

#6351 fix(types): propagate type parameter constraints for TypeScript 4.8
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/directives.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-core/src/vnode.ts
Labels: ready to merge

#7722 fix(playground): fix github button style
  packages/sfc-playground/src/Header.vue
Labels: ready to merge

#6294 types: update `TextareaHTMLAttributes` and `InputHTMLAttributes`
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#6212 types(shared): improve capitalize types
  packages/shared/src/general.ts
Labels: ready to merge, feat: types, :cake: p2-nice-to-have

#6177 test(reactivity): bigint test for non-observable values
  packages/reactivity/__tests__/reactive.spec.ts
Labels: ready to merge

#3848 fix(compiler-sfc): pass options directly to stylus
  packages/compiler-sfc/src/style/preprocessors.ts
Labels: ready to merge, feat: sfc

#5409 fix(compiler-sfc): v-bind using // to comment will still compile
  packages/compiler-sfc/src/style/cssVars.ts
Labels: ready to merge, feat: sfc-style-vars

#6160 types(runtime-dom): add missing `img` attr `loading`
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#6322 fix(runtime-dom): SVGAttributes style hint type error
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#7378 refactor(reactivity): use hasChanged to remove NaN
  packages/reactivity/src/collectionHandlers.ts
Labels: ready to merge, need test

#8386 chore: remove unnecessary type assertions
  packages/compiler-dom/src/decodeHtmlBrowser.ts
  packages/reactivity/src/ref.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-core/src/vnode.ts
Labels: ready to merge

#7432 fix(ssr): v-model w/ select
  packages/compiler-ssr/__tests__/ssrVModel.spec.ts
  packages/compiler-ssr/src/transforms/ssrVModel.ts
  packages/server-renderer/__tests__/ssrDirectives.spec.ts
Labels: ready to merge, feat: ssr, :hammer: p3-minor-bug

#7593 fix(compiler-sfc): check used import bindings for template `ref`
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/script/importUsageCheck.ts
Labels: ready to merge

#8090 types(jsx): add `inert` attribute and missing `hidden` values
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#7837 fix(runtime-core): `to` changes during teleport disabled cause update error
  packages/runtime-core/__tests__/components/Teleport.spec.ts
  packages/runtime-core/src/components/Teleport.ts
Labels: ready to merge, feat: teleport, :hammer: p3-minor-bug

#8328 dx(compiler-sfc): enhance `:deep` warnings
  packages/compiler-sfc/src/style/pluginScoped.ts
Labels: ready to merge

#8476 test(reactive): use vitest `vi.fn` instead of counting manually
  packages/reactivity/__tests__/ref.spec.ts
Labels: ready to merge

#8490 test: replace deprecated `initEvent`
  packages/runtime-dom/__tests__/directives/vOn.spec.ts
  packages/vue-compat/__tests__/utils.ts
Labels: ready to merge

#8506 refactor(shared): respect Promise A+ specification
  packages/shared/src/general.ts
Labels: ready to merge

#8512 perf: mark `defineComponent` as side-effects-free
  package.json
  packages/runtime-core/src/apiAsyncComponent.ts
  packages/runtime-core/src/apiDefineComponent.ts
  packages/runtime-dom/src/apiCustomElement.ts
  pnpm-lock.yaml
Labels: ready to merge

#8406 feat(nextTick): add nextTick function overload
  packages/runtime-core/__tests__/scheduler.spec.ts
  packages/runtime-core/src/scheduler.ts
  packages/shared/src/typeUtils.ts
Labels: ready to merge

#8602 types(withDefaults): improve the type of boolean attribute value
  packages/dts-test/setupHelpers.test-d.ts
  packages/runtime-core/src/apiSetupHelpers.ts
Labels: ready to merge

#8538 fix(compiler-sfc): take into account imports that are used within dynamic arguments
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/script/importUsageCheck.ts
Labels: ready to merge

#8535 fix(compiler-sfc): don't hoist props and emit
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineEmits.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/definePropsDestructure.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineEmits.spec.ts
  packages/compiler-sfc/__tests__/compileScript/definePropsDestructure.spec.ts
  packages/compiler-sfc/src/compileScript.ts
  packages/compiler-sfc/src/script/context.ts
  packages/compiler-sfc/src/script/defineEmits.ts
  packages/compiler-sfc/src/script/defineProps.ts
  packages/compiler-sfc/src/script/definePropsDestructure.ts
Labels: ready to merge

#8534 dx(compiler-sfc): warn when disabled defineModel
  packages/compiler-sfc/src/script/defineModel.ts
Labels: ready to merge

#8666 perf: cancel `MutationObserver` listener when disconnected
  packages/runtime-dom/src/apiCustomElement.ts
Labels: ready to merge
