Repository vuejs/core, pull requests merged in 2023-11, with the labels that each got.

#9451 feat(compiler-core): support shorthand syntax for v-bind
  packages/compiler-core/__tests__/transforms/vBind.spec.ts
  packages/compiler-core/src/transforms/vBind.ts
  packages/compiler-sfc/__tests__/__snapshots__/compileTemplate.spec.ts.snap
  packages/compiler-sfc/__tests__/compileTemplate.spec.ts
Labels: ready to merge, scope: compiler

#9495 fix(compiler-sfc): properly handle dynamic directive arguments usage check
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/script/importUsageCheck.ts
Labels: ready for review

#3962 fix(warn): avoid warning on empty children with Suspense
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/Suspense.ts
  packages/runtime-core/src/vnode.ts
Labels: ready to merge, scope: suspense, :cake: p2-nice-to-have

#6421 types(defineProps): remove optional properties from type
  packages/dts-test/setupHelpers.test-d.ts
  packages/runtime-core/src/apiSetupHelpers.ts
Labels: ready to merge, scope: types

#7004 fix(runtime-dom): `v-model` can update correctly when the element is an input of type number
  packages/runtime-dom/__tests__/directives/vModel.spec.ts
  packages/runtime-dom/src/directives/vModel.ts
Labels: ready to merge, scope: v-model, :cake: p2-nice-to-have

#7126 fix(hmr/transition): fix transition elements disappearing after reloa…
  packages/runtime-core/__tests__/hmr.spec.ts
  packages/runtime-core/src/components/BaseTransition.ts
Labels: ready to merge

#7245 fix(compiler-core): properly rewrite identifier of for
  packages/compiler-core/__tests__/transforms/__snapshots__/transformExpressions.spec.ts.snap
  packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
  packages/compiler-core/src/babelUtils.ts
Labels: ready to merge

#7315 fix(runtime-core): add name attribute of Teleport
  packages/runtime-core/src/components/Teleport.ts
Labels: ready to merge

#7316 fix(reactivity): clear on readonly collections return undefined
  packages/reactivity/__tests__/readonly.spec.ts
  packages/reactivity/__tests__/shallowReadonly.spec.ts
  packages/reactivity/src/collectionHandlers.ts
Labels: ready to merge

#7338 fix(types): props type is incompatible with setup returned type
  packages/dts-test/defineComponent.test-d.tsx
  packages/runtime-core/src/apiDefineComponent.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: ready to merge, scope: types, :hammer: p3-minor-bug

#7853 fix(reactivity): shallowRef type fix
  packages/dts-test/ref.test-d.ts
  packages/dts-test/watch.test-d.ts
  packages/reactivity/src/ref.ts
Labels: ready to merge, scope: types, :hammer: p3-minor-bug

#8527 fix(scripts): delete an unnecessary parameter
  scripts/build.js
Labels: ready to merge

#8568 chore: fix typos
  packages/compiler-core/src/parse.ts
  packages/compiler-ssr/src/index.ts
  packages/runtime-core/src/vnode.ts
Labels: ready to merge, :broom: p1-chore

#7937 fix(types): defining a custom element from the defined Component with emits
  packages/dts-test/defineCustomElement.test-d.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: ready to merge, scope: types, :hammer: p3-minor-bug

#7954 fix(types): allow undefined in `StyleValue`
  packages/dts-test/tsx.test-d.tsx
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#8607 fix(runtime-dom): update type definition for jsx
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#7608 dx(runtime-core): warn when the prop type is []
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentProps.ts
Labels: ready to merge

#7251 test(apiWatch): better indicate reactive obj pre & new values are the same
  packages/runtime-core/__tests__/apiWatch.spec.ts
Labels: ready to merge, :broom: p1-chore

#6700 refactor(compiler-dom): use String's built-in repeat method
  packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
Labels: ready to merge, :cake: p2-nice-to-have

#7866 dx(runtime-core): warn if `this` is used in a `<script setup>` template
  packages/runtime-core/__tests__/rendererComponent.spec.ts
  packages/runtime-core/src/componentRenderUtils.ts
Labels: ready to merge, scope: script-setup

#8065 test(shared): add test case
  packages/shared/__tests__/escapeHtml.spec.ts
Labels: ready to merge

#8012 types(runtime-dom): type for class property
  packages/dts-test/tsx.test-d.tsx
  packages/runtime-dom/src/jsx.ts
  packages/shared/__tests__/normalizeProp.spec.ts
Labels: ready to merge, scope: types

#8601 types(withDefaults): enhance read-only type
  packages/dts-test/setupHelpers.test-d.ts
  packages/runtime-core/src/apiSetupHelpers.ts
Labels: ready to merge

#9328 fix: hydration `__vnode` missing
  packages/runtime-core/src/hydration.ts
Labels: ready to merge, scope: ssr, 🔩 p2-edge-case

#8654 fix(compiler-sfc): consistently escape type-only prop names
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineProps.spec.ts
  packages/compiler-sfc/src/script/defineProps.ts
  packages/compiler-sfc/src/script/utils.ts
  packages/compiler-sfc/src/style/cssVars.ts
Labels: ready to merge

#8929 feat(compileStyle): support `:is` and `:where` selector
  packages/compiler-sfc/__tests__/compileStyle.spec.ts
  packages/compiler-sfc/src/style/pluginScoped.ts
Labels: ready to merge

#8655 fix(reactivity): onCleanup also needs to be cleaned
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: ready to merge

#8748 fix: update `unref` and `toValue` parameter type
  packages/reactivity/src/ref.ts
Labels: ready to merge

#9478 fix(compiler-sfc): malformed filename on windows using path.posix.join()
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: :exclamation: p4-important

#9321 refactor!: drop reactivity transform
  .eslintrc.cjs
  package.json
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/reactivityTransform.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/reactivityTransform.spec.ts
  packages/compiler-sfc/package.json
  packages/compiler-sfc/src/compileScript.ts
  packages/compiler-sfc/src/index.ts
  packages/compiler-sfc/src/script/definePropsDestructure.ts
  packages/compiler-sfc/src/script/normalScript.ts
  packages/dts-test/reactivityMacros.test-d.ts
  packages/reactivity-transform/LICENSE
  packages/reactivity-transform/README.md
  packages/reactivity-transform/__tests__/__snapshots__/reactivityTransform.spec.ts.snap
  packages/reactivity-transform/__tests__/reactivityTransform.spec.ts
  packages/reactivity-transform/package.json
  packages/reactivity-transform/src/babelPlugin.ts
  packages/reactivity-transform/src/index.ts
  packages/reactivity-transform/src/reactivityTransform.ts
  packages/sfc-playground/src/App.vue
  packages/vue/macros-global.d.ts
  packages/vue/package.json
  packages/vue/ref-macros.d.ts
  pnpm-lock.yaml
  scripts/pre-dev-sfc.js
Labels: ready to merge, version: minor

#9261 feat: use enum to replace const enum
  .eslintrc.cjs
  package.json
  packages/compiler-core/src/ast.ts
  packages/compiler-core/src/codegen.ts
  packages/compiler-core/src/compat/compatConfig.ts
  packages/compiler-core/src/errors.ts
  packages/compiler-core/src/options.ts
  packages/compiler-core/src/tokenizer.ts
  packages/compiler-core/src/utils.ts
  packages/compiler-dom/src/errors.ts
  packages/compiler-dom/src/transforms/stringifyStatic.ts
  packages/compiler-sfc/src/style/cssVars.ts
  packages/compiler-ssr/src/errors.ts
  packages/reactivity/src/constants.ts
  packages/reactivity/src/index.ts
  packages/reactivity/src/reactive.ts
  packages/runtime-core/src/compat/compatConfig.ts
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/componentProps.ts
  packages/runtime-core/src/componentPublicInstance.ts
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-core/src/devtools.ts
  packages/runtime-core/src/enums.ts
  packages/runtime-core/src/errorHandling.ts
  packages/runtime-core/src/hydration.ts
  packages/runtime-core/src/index.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-test/src/nodeOps.ts
  packages/shared/src/patchFlags.ts
  packages/shared/src/shapeFlags.ts
  packages/shared/src/slotFlags.ts
  packages/vue/macros.d.ts
  pnpm-lock.yaml
  rollup.config.js
  rollup.dts.config.js
  scripts/build.js
  scripts/const-enum.js
  scripts/dev.js
  scripts/inline-enums.js
  tsconfig.build.json
  tsconfig.json
Labels: :cake: p2-nice-to-have, ready for review

#9689 chore: fix typo
  packages/compiler-core/src/options.ts
  packages/compiler-core/src/parser.ts
  packages/compiler-core/src/tokenizer.ts
Labels: ready to merge, version: minor, easy for merge

#7018 feat(compiler-core): support Error in template
  packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
  packages/shared/src/globalsAllowList.ts
Labels: ready to merge, scope: compiler, version: minor, easy for merge

#8785 fix(compiler-core): support resolving components from props
  packages/compiler-core/__tests__/transforms/transformElement.spec.ts
  packages/compiler-core/src/transforms/transformElement.ts
Labels: ready to merge

#8883 fix(compiler-sfc): throw errors for loading TS
  packages/compiler-sfc/src/script/resolveType.ts
  packages/vue/compiler-sfc/register-ts.js
Labels: ready to merge

#9234 fix(runtime-core): expose events to props for functional components
  packages/dts-test/functionalComponent.test-d.tsx
  packages/runtime-core/src/component.ts
Labels: ready to merge, scope: types, :cake: p2-nice-to-have

#8704 chore: acceptable color in dark mode for custom formatter
  packages/runtime-core/src/customFormatter.ts
Labels: ready to merge

#9507 fix(compiler-sfc): generate more treeshaking friendly code
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineModel.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/definePropsDestructure.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineModel.spec.ts
  packages/compiler-sfc/__tests__/compileScript/definePropsDestructure.spec.ts
  packages/compiler-sfc/src/script/defineEmits.ts
  packages/compiler-sfc/src/script/defineProps.ts
Labels: ready to merge, :hammer: p3-minor-bug
