Repository vuejs/core, pull requests merged in 2023-03, with the labels that each got.

#7958 feat(types/jsx): support jsxImportSource, avoid global JSX conflict
  packages/dts-test/utils.d.ts
  packages/vue/jsx-runtime/dom.d.ts
  packages/vue/jsx-runtime/index.d.ts
  packages/vue/jsx-runtime/index.js
  packages/vue/jsx-runtime/index.mjs
  packages/vue/jsx-runtime/package.json
  packages/vue/jsx.d.ts
  packages/vue/package.json
  tsconfig.json
Labels: :exclamation: p4-important

#5738 feat(compiler-sfc): add defineOptions marco
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
  packages/runtime-core/src/apiSetupHelpers.ts
  packages/runtime-core/src/index.ts
  packages/runtime-core/types/scriptSetupHelpers.d.ts
Labels: feat: sfc

#5752 feat(complier-sfc): add `hoistStatic` for `<script setup>`
  packages/compiler-core/src/options.ts
  packages/compiler-core/src/transforms/transformElement.ts
  packages/compiler-core/src/transforms/transformExpression.ts
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/__snapshots__/compileScriptHoistStatic.spec.ts.snap
  packages/compiler-sfc/__tests__/__snapshots__/cssVars.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/__tests__/compileScriptHoistStatic.spec.ts
  packages/compiler-sfc/__tests__/compileScriptPropsTransform.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: ready to merge, feat: sfc

#7068 fix(compiler-sfc): analyze export default by AST
  packages/compiler-sfc/__tests__/rewriteDefault.spec.ts
  packages/compiler-sfc/src/compileScript.ts
  packages/compiler-sfc/src/index.ts
  packages/compiler-sfc/src/parse.ts
  packages/compiler-sfc/src/rewriteDefault.ts
Labels: :hammer: p3-minor-bug

#7339 fix(compiler-sfc): infer TS Extract&Exclude runtime type
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/src/compileScript.ts
Labels: ready to merge

#7974 fix(compiler-core): check if expression is constant
  packages/compiler-core/__tests__/transforms/transformExpressions.spec.ts
  packages/compiler-core/src/transforms/transformExpression.ts
Labels: :fire: p5-urgent, regression

#7972 fix(compiler-sfc): infer runtime type in defineProps
  packages/compiler-sfc/src/compileScript.ts
Labels: :hammer: p3-minor-bug
