Repository vuejs/core, pull requests merged in 2023-12, with the labels that each got.

#9734 types(withKeys): improve return type withKeys and withModifiers
  packages/dts-test/defineComponent.test-d.tsx
  packages/runtime-dom/src/directives/vOn.ts
Labels: scope: types, 🔩 p2-edge-case

#9724 fix(app): prevent template from being cached between apps with different options
  packages/vue/src/index.ts
Labels: scope: compiler, :hammer: p3-minor-bug

#9725 chore(playground): expose esm-browser files
  package.json
  packages/sfc-playground/vite.config.ts
Labels: scope: playground, 🔩 p2-edge-case

#3258 feat(props): provide props to validation
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentProps.ts
Labels: ready to merge, version: minor, :cake: p2-nice-to-have

#8989 fix(custom-element): correctly handle number type props in prod
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineProps.spec.ts
  packages/compiler-sfc/src/compileScript.ts
  packages/compiler-sfc/src/script/context.ts
  packages/compiler-sfc/src/script/defineProps.ts
Labels: ready to merge, scope: custom elements

#9731 fix(render): Prevent error when displaying symbol keys on a map
  packages/shared/__tests__/toDisplayString.spec.ts
  packages/shared/src/toDisplayString.ts
Labels: 🔩 p2-edge-case

#8786 feat(compiler-sfc): support import attributes and `using` syntax in TS
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
  packages/compiler-sfc/__tests__/utils.ts
  packages/compiler-sfc/src/rewriteDefault.ts
  packages/compiler-sfc/src/script/context.ts
Labels: ready to merge, version: minor

#8950 feat(compiler-core): add current filename to TransformContext
  packages/compiler-core/__tests__/transform.spec.ts
  packages/compiler-core/src/transform.ts
Labels: ready to merge, version: minor

#5953 feat(ssr): improve ssr hydration mismatch checks
  packages/compiler-core/__tests__/transform.spec.ts
  packages/compiler-core/src/transform.ts
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: scope: ssr

#9550 feat: add `__VUE_PROD_HYDRATION_MISMATCH_DETAILS__` flag
  packages/global.d.ts
  packages/runtime-core/src/featureFlags.ts
  packages/runtime-core/src/hydration.ts
  packages/vue/README.md
  rollup.config.js
  scripts/dev.js
  scripts/usage-size.ts
  vitest.config.ts
Labels: ready to merge

#9300 feat(runtime-dom): add `xmlns:xlink` to `SVGAttributes`
  packages/dts-test/tsx.test-d.tsx
  packages/runtime-dom/src/jsx.ts
  packages/shared/src/domAttrConfig.ts
Labels: ready to merge, scope: types, :cake: p2-nice-to-have

#2403 feat(types): expose `PublicProps` type
  packages/runtime-core/src/index.ts
Labels: ready to merge, scope: types, version: minor, :broom: p1-chore

#5408 feat(types): ComponentInstance type
  packages/dts-test/componentInstance.test-d.tsx
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/index.ts
Labels: ready to merge, scope: types, version: minor, :cake: p2-nice-to-have

#8644 types: add emits and slots type to `FunctionalComponent`
  packages/dts-test/component.test-d.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/componentEmits.ts
Labels: ready to merge, version: minor

#8374 types(defineSlots): Support for generic keyof slots
  packages/dts-test/setupHelpers.test-d.ts
  packages/runtime-core/src/componentSlots.ts
Labels: scope: types

#8998 fix(compiler-sfc): infer runtime type
  packages/compiler-sfc/src/script/resolveType.ts
Labels: ready to merge

#9045 feat(sfc-playground): add style to the active item
  packages/sfc-playground/src/Header.vue
  packages/sfc-playground/src/VersionSelect.vue
Labels: ready to merge

#9788 types(emits): simplify types
  packages/runtime-core/src/componentEmits.ts
Labels: scope: types, :broom: p1-chore

#8946 types: export object and function plugin
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/index.ts
Labels: ready to merge

#8909 types: export type AriaAttributes
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge

#9660 feat: add types when creating global directives
  packages/dts-test/appDirective.test-d.ts
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/compat/global.ts
Labels: ready to merge, scope: types, :cake: p2-nice-to-have

#9756 types(runtime-core): add `h` function overload
  packages/dts-test/h.test-d.ts
  packages/runtime-core/src/h.ts
Labels: ready to merge, scope: types, :cake: p2-nice-to-have

#8674 feat(sfc-playground): add reload function
  packages/sfc-playground/src/App.vue
  packages/sfc-playground/src/Header.vue
  packages/sfc-playground/src/icons/Reload.vue
Labels: ready to merge

#9824 fix(useCssVars): fix the loss of CSS variables during updates
  packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts
  packages/runtime-dom/src/helpers/useCssVars.ts
  packages/runtime-dom/src/modules/style.ts
Labels: ready for review

#9866 fix(compiler-core): fix crash when modifier is empty
  packages/compiler-core/__tests__/utils.spec.ts
  packages/compiler-core/src/utils.ts
Labels: 🔩 p2-edge-case

#8584 style: prefer `node:` protocol
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
Labels: ready for review

#9941 chore(apiWatch): use relative import location instead of package
  packages/runtime-core/src/apiWatch.ts
Labels: :broom: p1-chore
