Repository vuejs/core, pull requests merged in 2023-09, with the labels that each got.

#9089 fix(runtime-core): swap client/server debug labels
  packages/runtime-core/src/hydration.ts
Labels: ready to merge, scope: ssr, need discussion

#9112 ci: add autofix for pr
  .github/workflows/autofix.yml
  .github/workflows/ci.yml
  .github/workflows/size-data.yml
  .github/workflows/size-report.yml
Labels: ready to merge, :broom: p1-chore, need discussion, scope: infra

#8091 chore: configure renovate
  .github/dependabot.yml
  .github/renovate.json5
Labels: ready to merge
