Repository vuejs/core, pull requests merged in 2024-09, with the labels that each got.

#11748 chore(fix): clean script
  package.json
Labels: ready to merge, :broom: p1-chore, easy to merge

#11768 chore: document parameters of onWatcherCleanup
  packages/reactivity/src/effect.ts
  packages/reactivity/src/watch.ts
Labels: ready to merge, :broom: p1-chore

#11766 ci: prevents action from running on forks
  .github/workflows/ci.yml
  .github/workflows/size-data.yml
  .github/workflows/size-report.yml
Labels: ready to merge, :broom: p1-chore

#11746 test(reactive): use vitest fn instead of counting manually
  packages/reactivity/__tests__/ref.spec.ts
Labels: ready to merge, :broom: p1-chore, easy to merge

#11772 fix(hydration): handle text nodes with 0 during hydration
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: ready to merge, scope: ssr, :hammer: p3-minor-bug

#11722 fix(server-renderer): render `className` correctly
  packages/server-renderer/__tests__/ssrRenderAttrs.spec.ts
  packages/server-renderer/src/helpers/ssrRenderAttrs.ts
Labels: scope: ssr, :cake: p2-nice-to-have, ready for review

#11760 fix(reactivity): correctly handle method calls on user-extended arrays
  packages/reactivity/__tests__/reactiveArray.spec.ts
  packages/reactivity/src/arrayInstrumentations.ts
Labels: :lady_beetle: bug, scope: reactivity, ready for review

#10893 fix(server-renderer): Fix call to serverPrefetch in server renderer with an async setup
  packages/server-renderer/__tests__/render.spec.ts
  packages/server-renderer/src/render.ts
Labels: ready to merge, scope: ssr

#11656 fix(runtime-dom): prevent unnecessary DOM update from v-model
  packages/runtime-dom/__tests__/directives/vModel.spec.ts
  packages/runtime-dom/src/directives/vModel.ts
Labels: ready to merge, scope: v-model, :hammer: p3-minor-bug

#11699 fix(types/defineModel): allow getter and setter types to be unrelated
  packages-private/dts-test/setupHelpers.test-d.ts
  packages/runtime-core/src/apiSetupHelpers.ts
  packages/runtime-core/src/helpers/useModel.ts
Labels: scope: types, ready for review

#11657 fix(runtime-dom): avoid unnecessary prop patch for checkbox
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/modules/props.ts
Labels: ready to merge, scope: v-model, :hammer: p3-minor-bug

#11794 fix(reactivity): handle non-array arguments in reactive `concat` method
  packages/reactivity/__tests__/reactiveArray.spec.ts
  packages/reactivity/src/arrayInstrumentations.ts
Labels: :lady_beetle: bug, ready to merge, scope: reactivity, :exclamation: p4-important

#11799 types(runtime-core): using intersection type in `Readonly<...>` breaks JSDoc emit
  packages/runtime-core/src/apiDefineComponent.ts
  packages/runtime-core/src/componentOptions.ts
Labels: ready to merge, scope: types, :exclamation: p4-important

#11820 types(shared): removed the Awaited compatibility type tool
  packages/runtime-core/src/scheduler.ts
  packages/shared/src/typeUtils.ts
Labels: ready to merge, scope: types

#11813 fix(reactivity): pass oldValue to computed getter
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/effect.ts
Labels: ready to merge, scope: reactivity, :exclamation: p4-important

#11778 fix(Transition): handle KeepAlive child unmount in Transition out-in mode
  packages/runtime-core/src/componentRenderUtils.ts
  packages/runtime-core/src/components/BaseTransition.ts
  packages/runtime-core/src/components/KeepAlive.ts
  packages/vue/__tests__/e2e/Transition.spec.ts
Labels: scope: transition, :hammer: p3-minor-bug, ready for review

#11797 fix(reactivity): prevent endless recursion in computed getters
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/dep.ts
Labels: need test, scope: reactivity

#11818 fix(suspense): avoid updating anchor if activeBranch has not been rendered to the actual container
  packages/runtime-core/src/components/Suspense.ts
  packages/vue/__tests__/e2e/Transition.spec.ts
Labels: ready to merge, scope: suspense, :hammer: p3-minor-bug

#11819 feat(compiler-core): parse modifiers as expression to provide location data
  packages/compiler-core/__tests__/parse.spec.ts
  packages/compiler-core/src/ast.ts
  packages/compiler-core/src/parser.ts
  packages/compiler-core/src/transforms/transformElement.ts
  packages/compiler-core/src/transforms/vBind.ts
  packages/compiler-core/src/transforms/vModel.ts
  packages/compiler-dom/src/transforms/vOn.ts
Labels: ready to merge, scope: compiler

#11825 fix(Hydration): implement proper check for __asyncHydrate
  packages/runtime-core/src/renderer.ts
Labels: ready to merge, scope: ssr

#11840 fix(runtime-core): correctly infer `TypeEmits` with both tuple and function syntax
  packages/runtime-core/src/componentEmits.ts
Labels: ready to merge, scope: types

#11842 chore: remove unused variable
  packages/compiler-core/src/transform.ts
  packages/compiler-core/src/transforms/vIf.ts
Labels: ready to merge, :broom: p1-chore, easy to merge

#11854 feat(compiler-sfc): correct scoped injection for nesting selector
  packages/compiler-sfc/__tests__/compileStyle.spec.ts
  packages/compiler-sfc/src/style/pluginScoped.ts
Labels: ready to merge, scope: sfc, :cake: p2-nice-to-have

#11864 fix(reactive): markRaw function return the value directly when it has been marked
  packages/reactivity/__tests__/reactive.spec.ts
  packages/reactivity/src/reactive.ts
Labels: ready to merge, scope: reactivity, :cake: p2-nice-to-have

#11870 fix(runtime-core): handle shallow reactive arrays in renderList correctly
  packages/runtime-core/__tests__/helpers/renderList.spec.ts
  packages/runtime-core/src/helpers/renderList.ts
Labels: ready to merge, :exclamation: p4-important

#11695 perf(reactivity): trigger item directly instead of storing in an array first
  packages/reactivity/src/dep.ts
Labels: scope: reactivity, :cake: p2-nice-to-have, ready for review

#11856 refactor(scheduler): simplify checkRecursiveUpdates
  packages/runtime-core/src/scheduler.ts
Labels: ready to merge, :broom: p1-chore

#11428 chore(sfc-playground): editor can modify whether auto-save is enabled
  packages-private/sfc-playground/package.json
  packages-private/sfc-playground/src/App.vue
  packages-private/sfc-playground/src/Header.vue
  pnpm-lock.yaml
Labels: ready to merge, scope: playground

#11915 fix(compiler-core): fix handling of delimiterOpen in VPre
  packages/compiler-core/__tests__/parse.spec.ts
  packages/compiler-core/src/tokenizer.ts
Labels: ready to merge, scope: compiler, :cake: p2-nice-to-have

#11899 fix(compiler-sfc): nested css supports atrule and comment
  packages/compiler-sfc/__tests__/compileStyle.spec.ts
  packages/compiler-sfc/src/style/pluginScoped.ts
Labels: :lady_beetle: bug, scope: sfc, ready for review

#11917 fix(runtime-core): properly update async component nested in KeepAlive
  packages/runtime-core/__tests__/apiAsyncComponent.spec.ts
  packages/runtime-core/src/apiAsyncComponent.ts
Labels: ready to merge, :exclamation: p4-important

#11888 fix(TransitionGroup): not warn unkeyed text children with whitespece preserve
  packages/runtime-dom/src/components/TransitionGroup.ts
  packages/vue/__tests__/e2e/TransitionGroup.spec.ts
Labels: ready to merge, scope: transition, :cake: p2-nice-to-have

#11861 fix(custom-element): handle nested customElement mount w/ shadowRoot false
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
  packages/vue/__tests__/e2e/ssr-custom-element.spec.ts
Labels: ready to merge, :exclamation: p4-important, scope: custom elements

#11907 fix(hmr): reload async child wrapped in Suspense + KeepAlive
  packages/runtime-core/__tests__/hmr.spec.ts
  packages/runtime-core/src/hmr.ts
  packages/runtime-core/src/renderer.ts
Labels: ready to merge, scope: hmr, ready for review

#11933 refactor(reactivity): simplify isDirty condition
  packages/reactivity/src/effect.ts
Labels: ready to merge, :broom: p1-chore

#11931 fix(reactivity): rely on dirty check only when computed has deps
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/effect.ts
Labels: ready to merge, scope: reactivity, :exclamation: p4-important

#11926 chore(types): update directive types
  packages-private/dts-test/appDirective.test-d.ts
  packages/runtime-core/src/apiCreateApp.ts
Labels: ready to merge, scope: types, :cake: p2-nice-to-have

#11904 chore(types): migrate global types to packages-private
  packages-private/global.d.ts
  packages/global.d.ts
Labels: ready to merge, scope: types, :broom: p1-chore

#11925 fix(runtime-core): unwatch should be callable during SSR
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :lady_beetle: bug, scope: ssr, :exclamation: p4-important, regression

#11884 fix(watch): `once` option should be ignored by watchEffect
  packages/reactivity/__tests__/watch.spec.ts
  packages/reactivity/src/watch.ts
Labels: ready for review

#11891 feat(compile-dom): stringify mathML
  packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
  packages/compiler-dom/src/transforms/stringifyStatic.ts
  packages/shared/src/domAttrConfig.ts
Labels: ready to merge, scope: sfc

#11954 fix(hydration): avoid observing non-Element node
  packages/runtime-core/src/hydrationStrategies.ts
  packages/vue/__tests__/e2e/hydration-strat-visible.html
  packages/vue/__tests__/e2e/hydrationStrategies.spec.ts
Labels: ready to merge, :hammer: p3-minor-bug, scope:hydration

#11955 fix(scheduler): ensure recursive jobs can't be queued twice
  packages/runtime-core/__tests__/scheduler.spec.ts
  packages/runtime-core/src/scheduler.ts
Labels: ready to merge

#11963 fix(compiler-sfc): initialize scope with null prototype object
  packages/compiler-sfc/src/script/definePropsDestructure.ts
Labels: ready to merge, :broom: p1-chore, easy to merge

#11970 fix(sfc-playground): resolve autosave conflict issue
  packages-private/sfc-playground/src/App.vue
Labels: ready to merge, :broom: p1-chore, scope: playground

#11960 fix(compile-core): fix v-model with newlines edge case
  packages/compiler-core/src/transforms/vModel.ts
  packages/compiler-sfc/__tests__/__snapshots__/compileScript.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript.spec.ts
Labels: ready to merge, scope: compiler, scope: v-model, :cake: p2-nice-to-have

#11961 fix(ssr): don't render comments in TransitionGroup
  packages/compiler-ssr/__tests__/ssrTransitionGroup.spec.ts
  packages/compiler-ssr/src/ssrCodegenTransform.ts
  packages/compiler-ssr/src/transforms/ssrVIf.ts
Labels: :lady_beetle: bug, ready to merge, scope: transition

#11967 fix(transition): respect `duration` setting even when it is `0`
  packages/runtime-dom/src/components/Transition.ts
Labels: ready to merge, scope: transition, 🔩 p2-edge-case

#11644 fix(runtime-core): correct type inference of all-optional props
  packages/runtime-core/src/apiDefineComponent.ts
  packages/runtime-core/src/componentProps.ts
Labels: scope: types, ready for review

#11995 fix(reactivity): do not remove dep from depsMap when cleaning up deps of computed
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/effect.ts
Labels: ready to merge, scope: reactivity, :exclamation: p4-important

#12006 chore: remove unused argument
  packages/runtime-dom/src/directives/vModel.ts
Labels: ready to merge, :broom: p1-chore

#12007 fix(reactivity): optimising getDepFromReactive
  packages/reactivity/src/dep.ts
Labels: ready to merge, :broom: p1-chore

#12022 fix(types): correct type inference of union event names
  packages/runtime-core/src/componentEmits.ts
Labels: scope: types

#12019 fix(vue): properly cache runtime compilation
  packages/compiler-sfc/src/parse.ts
  packages/shared/src/general.ts
  packages/vue-compat/src/index.ts
  packages/vue/src/index.ts
Labels: ready to merge, :hammer: p3-minor-bug

#12038 fix(runtime-core): avoid rendering plain object as VNode
  packages/runtime-core/__tests__/rendererChildren.spec.ts
  packages/runtime-core/src/vnode.ts
Labels: ready to merge, :cake: p2-nice-to-have
