Repository vuejs/core, pull requests merged in 2024-04, with the labels that each got.

#9573 chore: update VSCode debugging for vitest
  .vscode/launch.json
Labels: :broom: p1-chore

#10599 fix(runtime-core): show hydration mismatch details for non-rectified mismatches too when __PROD_HYDRATION_MISMATCH_DETAILS__ is set
  .gitignore
  packages/runtime-core/src/hydration.ts
Labels: ready to merge, scope: ssr, :cake: p2-nice-to-have

#10637 fix(compiler-sfc): also search for `.tsx` when type import's extension is omitted
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: ready to merge, scope: types, scope: compiler, 🔩 p2-edge-case

#9421 fix(TransitionGroup): avoid set transition hooks for comment nodes and text nodes
  packages/runtime-dom/src/components/TransitionGroup.ts
  packages/vue/__tests__/e2e/TransitionGroup.spec.ts
Labels: :hammer: p3-minor-bug, ready for review

#8550 chore: add download badge
  README.md
Labels: :broom: p1-chore, ready for review

#10518 fix(compile-sfc): analyze v-bind shorthand usage in template
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/importUsageCheck.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/importUsageCheck.spec.ts
  packages/compiler-sfc/src/script/importUsageCheck.ts
Labels: scope: sfc, :hammer: p3-minor-bug, ready for review

#10551 fix(compiler-sfc): fix universal selector scope
  packages/compiler-sfc/__tests__/compileStyle.spec.ts
  packages/compiler-sfc/src/style/pluginScoped.ts
Labels: ready to merge, scope: compiler, :hammer: p3-minor-bug

#9603 fix(compiler-sfc): fixed the type compilation of defineModel in the prod
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineModel.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineModel.spec.ts
  packages/compiler-sfc/src/script/defineModel.ts
Labels: ready to merge, scope: compiler

#10638 fix(hydration): properly handle optimized mode during hydrate node
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: :lady_beetle: bug, scope: ssr, ready for review

#6732 fix(ssr): don't render v-if comments in TransitionGroup
  packages/compiler-ssr/__tests__/ssrTransitionGroup.spec.ts
  packages/compiler-ssr/src/ssrCodegenTransform.ts
  packages/compiler-ssr/src/transforms/ssrTransformTransitionGroup.ts
  packages/compiler-ssr/src/transforms/ssrVIf.ts
Labels: :hammer: p3-minor-bug

#10506 fix(runtime-dom): equal value with a leading 0 do not trigger update
  packages/runtime-dom/__tests__/directives/vModel.spec.ts
  packages/runtime-dom/src/directives/vModel.ts
Labels: scope: v-model

#10632 fix(Transition): ensure the KeepAlive children unmount w/ out-in mode
  packages/runtime-core/__tests__/components/BaseTransition.spec.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: :lady_beetle: bug, scope: transition, ready for review

#10705 chore: update to ESLint 9
  .eslintignore
  .eslintrc.cjs
  .github/renovate.json5
  eslint.config.js
  package.json
  packages/compiler-core/__tests__/parse.spec.ts
  packages/runtime-core/src/components/Suspense.ts
  pnpm-lock.yaml
  scripts/release.js
Labels: :broom: p1-chore, ready for review

#10501 fix(reactivity): fix call sequence of ontrigger in effect
  packages/reactivity/__tests__/effect.spec.ts
  packages/reactivity/src/dep.ts
Labels: scope: reactivity

#3399 types(defineComponent): Support for GlobalComponents, typed Directives and respect `expose` on defineComponent
  packages/dts-test/componentTypeExtensions.test-d.tsx
  packages/dts-test/defineComponent.test-d.tsx
  packages/dts-test/directives.test-d.ts
  packages/runtime-core/src/apiDefineComponent.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/componentPublicInstance.ts
  packages/runtime-core/src/directives.ts
  packages/runtime-core/src/index.ts
  packages/runtime-core/types/globalComponents.d.ts
  packages/runtime-dom/__tests__/directives/vOn.spec.ts
  packages/runtime-dom/src/directives/vModel.ts
  packages/runtime-dom/src/directives/vOn.ts
  packages/runtime-dom/src/index.ts
  packages/vue-compat/__tests__/instance.spec.ts
Labels: scope: types, version: minor, :cake: p2-nice-to-have

#10767 fix(runtime-core): attrs should be readonly in functional components
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentRenderUtils.ts
Labels: ready for review

#10809 fix(runtime-core): properly handle inherit transition during clone VNode
  packages/runtime-core/src/componentRenderUtils.ts
  packages/runtime-core/src/vnode.ts
  packages/vue/__tests__/e2e/Transition.spec.ts
Labels: :lady_beetle: bug, ready for review

#4619 feat(runtime-core): app.onUnmount() for registering cleanup functions (close: #4516)
  packages/runtime-core/__tests__/apiCreateApp.spec.ts
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/errorHandling.ts
Labels: :sparkles: feature request, ready for review

#5789 fix(compiler-core): add support for arrow aysnc function with unbracketed
  packages/compiler-core/__tests__/transforms/vOn.spec.ts
  packages/compiler-core/src/transforms/vOn.ts
Labels: scope: compiler, ready for review
