Repository vuejs/core, pull requests merged in 2024-06, with the labels that each got.

#7513 test(reactivity): replace isReactive with isReadonly
  packages/reactivity/__tests__/readonly.spec.ts
Labels: ready to merge, scope: reactivity, :broom: p1-chore, easy for merge

#8210 fix(reactivity): Pass oldValue to triggerRefValue to satisfy interface DebuggerEventExtraInfo
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/ref.ts
Labels: ready to merge, :cake: p2-nice-to-have, easy for merge

#8304 fix(runtime-core): fix missed updates when passing text vnode to <component :is>
  packages/runtime-core/__tests__/vnode.spec.ts
  packages/runtime-core/src/vnode.ts
Labels: :lady_beetle: bug, ready to merge

#9174 test(reactivity): should not observe well-known symbol keyed properties in has operation
  packages/reactivity/__tests__/effect.spec.ts
Labels: :broom: p1-chore

#9503 test(effect): verify cleanupEffect clears multiple dependencies
  packages/reactivity/__tests__/effect.spec.ts
Labels: :broom: p1-chore

#9615 fix(runtime-dom): compatibility of createElement in older versions of Chrome (#9614)
  packages/runtime-dom/__tests__/nodeOps.spec.ts
  packages/runtime-dom/src/nodeOps.ts
Labels: scope: custom elements

#11056 chore: use PropertyKey type
  packages/reactivity/src/reactiveEffect.ts
  packages/runtime-core/src/apiSetupHelpers.ts
  packages/runtime-core/src/compat/global.ts
  packages/runtime-core/src/components/KeepAlive.ts
  packages/runtime-core/src/helpers/useModel.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-core/src/vnode.ts
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge, :broom: p1-chore

#9370 fix(runtime-core): do not fire lifecycle hooks during unmounting
  packages/runtime-core/__tests__/apiLifecycle.spec.ts
  packages/runtime-core/src/apiLifecycle.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/components/KeepAlive.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-core/src/scheduler.ts
Labels: :hammer: p3-minor-bug

#9403 fix(hydration): log hydration error even when using async components
  packages/runtime-core/src/hydration.ts
Labels: scope: ssr, :hammer: p3-minor-bug

#10921 fix(compiler-sfc): fix type inference issue with the keyof operator
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: scope: types, :hammer: p3-minor-bug

#6606 fix(runtime-core): improve v-memo work with v-if
  packages/runtime-core/__tests__/helpers/withMemo.spec.ts
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/helpers/withMemo.ts
  packages/runtime-core/src/renderer.ts
  packages/runtime-core/src/vnode.ts
Labels: :hammer: p3-minor-bug

#10908 fix(compile-sfc): Support project reference with folder, fix #10907
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: scope: sfc, :cake: p2-nice-to-have

#10883 refactor(shared): improve start/end handling in generateCodeFrame
  packages/shared/__tests__/__snapshots__/codeframe.spec.ts.snap
  packages/shared/__tests__/codeframe.spec.ts
  packages/shared/src/codeframe.ts
Labels: scope: compiler, 🔩 p2-edge-case

#11036 fix(apiWatch): correct type inference for reactive array
  packages/dts-test/reactivity.test-d.ts
  packages/dts-test/watch.test-d.ts
  packages/reactivity/src/index.ts
  packages/reactivity/src/reactive.ts
  packages/runtime-core/src/apiWatch.ts
  packages/runtime-core/src/index.ts
Labels: scope: types

#10603 fix(types): fix `app.provide` type checking
  packages/dts-test/inject.test-d.ts
  packages/runtime-core/src/apiCreateApp.ts
Labels: scope: types, 🔩 p2-edge-case

#10608 fix(runtime-dom): use Symbol value for checkbox true-value #10597
  packages/runtime-dom/__tests__/patchAttrs.spec.ts
  packages/runtime-dom/src/modules/attrs.ts
  packages/runtime-dom/src/modules/props.ts
Labels: :cake: p2-nice-to-have

#11165 fix(patchProp): prevent setting state as attribute for custom elements
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/patchProp.ts
Labels: :exclamation: p4-important, scope: custom elements

#11171 fix(runtime-core): ensure unmount dynamic components in optimized mode
  packages/runtime-core/__tests__/rendererOptimizedMode.spec.ts
  packages/runtime-core/src/renderer.ts
Labels: :hammer: p3-minor-bug

#11145 refactor(effect): cache tracking value
  packages/reactivity/src/effect.ts
Labels: :broom: p1-chore

#11182 fix(runtime-dom): ensure only symbols are explicitly stringified during attribute patching
  packages/runtime-dom/__tests__/patchAttrs.spec.ts
  packages/runtime-dom/src/modules/attrs.ts
Labels: :hammer: p3-minor-bug, scope: custom elements

#11139 refactor(built-ins): remove unused code from Teleport and Suspense components
  packages/runtime-core/src/components/Suspense.ts
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-core/src/renderer.ts
Labels: :broom: p1-chore

#7306 fix(shared): unwrap refs in toDisplayString
  packages/shared/__tests__/toDisplayString.spec.ts
  packages/shared/src/toDisplayString.ts
Labels: :cake: p2-nice-to-have, ready for review
