Repository vuejs/core, pull requests merged in 2024-03, with the labels that each got.

#10443 types: fix `scroll` event type; add support for `scrollend`
  packages/runtime-dom/src/jsx.ts
Labels: scope: types, :cake: p2-nice-to-have

#9086 chore(playground): save `tsconfig.json` to the root directory; update Node.js version requirement
  packages/sfc-playground/src/download/download.ts
  packages/sfc-playground/src/download/template/README.md
Labels: ready to merge, scope: playground

#9053 perf: add `__NO_SIDE_EFFECTS__` comments
  packages/runtime-core/src/devtools.ts
  packages/server-renderer/src/helpers/ssrRenderAttrs.ts
  packages/shared/src/makeMap.ts
Labels: ready to merge, :cake: p2-nice-to-have

#8558 types: make instrumentations' types more succinct
  packages/reactivity/src/collectionHandlers.ts
Labels: :broom: p1-chore, ready for review

#8844 test: create `EffectScope` using a factory function
  packages/reactivity/__tests__/effectScope.spec.ts
Labels: ready to merge

#9012 fix(custom-element): avoid setting attr to null if it is removed
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: ready to merge, :hammer: p3-minor-bug, scope: custom elements

#9575 fix(runtime-core): fix errorHandler causes an infinite loop during execution
  packages/runtime-core/__tests__/errorHandling.spec.ts
  packages/runtime-core/src/errorHandling.ts
Labels: :hammer: p3-minor-bug

#10522 fix(compiler-sfc): :is() and :where() in compound selectors
  packages/compiler-sfc/__tests__/compileStyle.spec.ts
  packages/compiler-sfc/src/style/pluginScoped.ts
Labels: scope: compiler, ready for review

#10576 fix(runtime-dom): `v-model` string/number coercion for multiselect options
  packages/runtime-dom/__tests__/directives/vModel.spec.ts
  packages/runtime-dom/src/directives/vModel.ts
Labels: scope: v-model, :hammer: p3-minor-bug
