Repository vuejs/core, pull requests merged in 2024-10, with the labels that each got.

#12075 fix(reactivity): prevent overwriting `next` property during batch processing
  packages/reactivity/__tests__/watch.spec.ts
  packages/reactivity/src/computed.ts
  packages/reactivity/src/effect.ts
Labels: ready to merge, scope: reactivity, :exclamation: p4-important

#12090 fix(scheduler): job ordering when the post queue is flushing
  packages/runtime-core/__tests__/scheduler.spec.ts
  packages/runtime-core/src/scheduler.ts
Labels: ready to merge

#12073 fix(types): correctly infer `TypeProps` when it is `any`
  packages/runtime-core/src/apiDefineComponent.ts
  packages/shared/src/typeUtils.ts
Labels: ready to merge, scope: types

#12077 fix(types): should not intersect `PublicProps` with `Props`
  packages/runtime-core/src/apiDefineComponent.ts
Labels: ready to merge, scope: types

#12143 fix(customElement): properly remove hyphenated attribute
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/modules/props.ts
  packages/runtime-dom/src/patchProp.ts
Labels: ready to merge, :hammer: p3-minor-bug, scope: custom elements

#12069 fix(runtime-core): allow symbol values for slot prop key
  packages/runtime-core/__tests__/helpers/renderSlot.spec.ts
  packages/runtime-core/src/helpers/renderSlot.ts
Labels: ready to merge, :hammer: p3-minor-bug

#12123 fix(types): ensure `this.$props` type does not include `string`
  packages-private/dts-test/defineComponent.test-d.tsx
  packages/runtime-core/src/apiDefineComponent.ts
Labels: ready to merge, scope: types

#12116 chore(sfc-playground): adjust the tooltip text for toggling the theme
  packages-private/sfc-playground/src/App.vue
  packages-private/sfc-playground/src/Header.vue
Labels: ready to merge, :broom: p1-chore, scope: playground

#12047 fix(transition/ssr): make transition appear work with Suspense in SSR
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: ready to merge, scope: transition, scope: ssr, :hammer: p3-minor-bug

#12063 fix(runtime-core): handle kebab-case model correctly
  packages/runtime-core/__tests__/helpers/useModel.spec.ts
  packages/runtime-core/src/helpers/useModel.ts
Labels: ready to merge, :hammer: p3-minor-bug

#12055 fix(reactivity): trigger reactivity for Map key `undefined`
  packages/reactivity/__tests__/reactive.spec.ts
  packages/reactivity/src/dep.ts
Labels: ready to merge, scope: reactivity, :cake: p2-nice-to-have

#12096 fix(compiler-dom): avoid stringify `<option>` with null value
  packages/compiler-dom/__tests__/transforms/__snapshots__/stringifyStatic.spec.ts.snap
  packages/compiler-dom/__tests__/transforms/stringifyStatic.spec.ts
  packages/compiler-dom/src/transforms/stringifyStatic.ts
Labels: ready to merge, scope: compiler, :hammer: p3-minor-bug

#12135 perf(reactivity): avoid unnecessary recursion in removeSub
  packages/reactivity/__tests__/computed.spec.ts
  packages/reactivity/src/effect.ts
Labels: ready to merge, scope: reactivity, :cake: p2-nice-to-have

#12128 fix(useId): ensure useId consistency when using serverPrefetch
  packages/runtime-core/__tests__/helpers/useId.spec.ts
  packages/runtime-core/src/component.ts
Labels: ready to merge, scope: ssr, :hammer: p3-minor-bug

#12113 fix(runtime-core): handle disabled teleport with updateCssVars
  packages/runtime-core/src/components/Teleport.ts
  packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts
Labels: ready to merge, scope: teleport

#12064 fix(compiler-sfc): do not skip TSInstantiationExpression when transforming props destructure
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/definePropsDestructure.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/definePropsDestructure.spec.ts
  packages/compiler-sfc/src/script/definePropsDestructure.ts
Labels: ready to merge, scope: sfc, :cake: p2-nice-to-have

#12051 chore(runtime-core): warn if use a non-ref to hold the element reference in DEV
  packages/runtime-core/__tests__/rendererTemplateRef.spec.ts
  packages/runtime-core/src/rendererTemplateRef.ts
Labels: ready to merge, :broom: p1-chore

#12034 fix(runtime-core): use camelized prop key to check if it is absent
  packages/runtime-core/__tests__/componentProps.spec.ts
  packages/runtime-core/src/componentProps.ts
Labels: ready to merge, :cake: p2-nice-to-have

#11992 refactor(compiler-sfc): support sass modern api
  packages/compiler-sfc/src/style/preprocessors.ts
Labels: ready to merge, scope: compiler

#12131 fix(compiler): clone loc to `ifNode`
  packages/compiler-core/src/parser.ts
  packages/compiler-core/src/transforms/vIf.ts
Labels: ready to merge, scope: compiler, :broom: p1-chore

#11935 fix(hydration): provide compat fallback for idle callback
  packages/runtime-core/src/hydrationStrategies.ts
Labels: ready to merge, :cake: p2-nice-to-have

#11328 refactor(reactivity): unnecessarily func call
  packages/reactivity/__tests__/reactiveArray.spec.ts
Labels: ready to merge, scope: reactivity, :broom: p1-chore

#12146 fix(runtime-dom): prevent unnecessary updates in v-model checkbox when value is unchanged
  packages/runtime-dom/src/directives/vModel.ts
  packages/vue/__tests__/e2e/vModel.spec.ts
Labels: scope: v-model, :exclamation: p4-important

#8684 test(defineProps): add intersection type test
  packages/compiler-sfc/__tests__/compileScript/__snapshots__/defineProps.spec.ts.snap
  packages/compiler-sfc/__tests__/compileScript/defineProps.spec.ts
Labels: ready to merge, :broom: p1-chore

#8456 test(shared): improve test coverage
  packages/shared/__tests__/normalizeProp.spec.ts
Labels: ready to merge, :broom: p1-chore

#10914 chore: improve `renderComponentRoot` warn message
  packages/runtime-core/__tests__/rendererAttrsFallthrough.spec.ts
  packages/runtime-core/src/componentRenderUtils.ts
Labels: ready to merge, :cake: p2-nice-to-have
