Repository vuejs/core, pull requests merged in 2024-08, with the labels that each got.

#9572 feat(apiWatch): support passing the `number` type for `deep` to control the watch depth
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :sparkles: feature request, scope: reactivity, version: minor

#9336 fix(types): Use alternative Omit that enables discriminated unions in props
  packages/dts-test/setupHelpers.test-d.ts
Labels: scope: types, :cake: p2-nice-to-have

#9563 chore(runtime-core): export `MultiWatchSources` type
  packages/runtime-core/src/apiWatch.ts
  packages/runtime-core/src/index.ts
Labels: ready to merge, scope: types, version: minor, :cake: p2-nice-to-have

#10844 feat(runtime-dom): a new `__VUE_PROD_TRUSTED_TYPES__` flag for trusted types compatibility
  package.json
  packages/runtime-core/src/compat/global.ts
  packages/runtime-dom/package.json
  packages/runtime-dom/src/index.ts
  packages/runtime-dom/src/nodeOps.ts
  packages/vue/__tests__/e2e/trusted-types.html
  packages/vue/__tests__/e2e/trusted-types.spec.ts
  pnpm-lock.yaml
Labels: version: minor, ready for review

#9651 feat(reactivity): add `pause/resume` methods to `ReactiveEffect`
  packages/reactivity/__tests__/effect.spec.ts
  packages/reactivity/__tests__/effectScope.spec.ts
  packages/reactivity/src/effect.ts
  packages/reactivity/src/effectScope.ts
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
  packages/runtime-core/src/index.ts
Labels: :sparkles: feature request, scope: reactivity, version: minor

#6256 feat(customElement): support for expose on customElement, fix #5540
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: version: minor, scope: custom elements

#11384 fix(types): `defineCustomElement` props inference with array emits
  packages/dts-test/defineCustomElement.test-d.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: scope: types, scope: custom elements

#11522 chore: fix typo
  packages/runtime-core/src/component.ts
  packages/runtime-core/src/hmr.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: ready to merge, easy for merge

#11515 fix(ssr): don't render v-if comments in TransitionGroup + static tag
  packages/compiler-ssr/__tests__/ssrTransitionGroup.spec.ts
  packages/compiler-ssr/src/transforms/ssrTransformTransitionGroup.ts
Labels: scope: transition, scope: ssr, :hammer: p3-minor-bug, ready for review

#9690 workflow: add a "publish" workflow for automated releases
  .github/workflows/publish.yml
  scripts/release.js
Labels: ready for review, scope: infra

#8830 feat(custom-element): Support css `:host` selector
  packages/runtime-dom/__tests__/helpers/useCssVars.spec.ts
  packages/runtime-dom/src/helpers/useCssVars.ts
Labels: scope: custom elements

#11536 fix(types/ref): correct type inference for nested refs
  packages/dts-test/ref.test-d.ts
  packages/reactivity/src/ref.ts
Labels: scope: types, :hammer: p3-minor-bug

#11479 fix(KeepAlive): avoid cache suspense comment root
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: scope: keep-alive, scope: suspense, :hammer: p3-minor-bug, ready for review

#11491 fix(ssr): ensure content is valid when rendering normal slot
  packages/runtime-core/src/helpers/renderSlot.ts
  packages/runtime-core/src/index.ts
  packages/server-renderer/__tests__/ssrSlot.spec.ts
  packages/server-renderer/src/helpers/ssrRenderSlot.ts
Labels: scope: slots, scope: ssr, :hammer: p3-minor-bug, ready for review

#11496 fix(keepalive): render fails when cache contains undefined
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: scope: keep-alive, :hammer: p3-minor-bug, ready for review

#11502 fix(runtime-core): prioritize using the provides from currentApp in nested createApp
  packages/runtime-core/__tests__/apiCreateApp.spec.ts
  packages/runtime-core/src/apiInject.ts
Labels: :hammer: p3-minor-bug, ready for review

#11540 fix(types): allow `DirectiveArguments` third parameter to accept undefined
  packages/runtime-core/src/directives.ts
Labels: ready to merge, scope: types, easy for merge

#11543 fix(defineModel): detect changes respect custom getter and setter
  packages/runtime-core/__tests__/helpers/useModel.spec.ts
  packages/runtime-core/src/helpers/useModel.ts
Labels: need guidance

#11547 fix(compiler-core): initialize `isProp.exp` with `arg.loc` instead of `isProp.loc`
  packages/compiler-core/src/transforms/transformElement.ts
Labels: ready to merge, scope: compiler, easy for merge

#11572 fix(reactivity): avoid wrapping extended array methods
  packages/reactivity/__tests__/reactiveArray.spec.ts
  packages/reactivity/src/arrayInstrumentations.ts
Labels: scope: reactivity, version: minor, :exclamation: p4-important

#11574 fix(reactivity): ensure extended method arguments are not lost
  packages/reactivity/__tests__/reactiveArray.spec.ts
  packages/reactivity/src/arrayInstrumentations.ts
Labels: :lady_beetle: bug, scope: reactivity, version: minor, ready for review

#11596 chore: add explicit type annotation to `initDirectivesForSSR`
  packages/runtime-dom/src/index.ts
Labels: ready to merge, :broom: p1-chore, easy for merge

#11599 perf: remove unnecessary check as filter is always non-null
  packages/runtime-core/src/components/KeepAlive.ts
Labels: ready to merge, scope: keep-alive, :broom: p1-chore, easy for merge

#11595 fix(keep-alive): optimize the matching rules when regexp carry flags
  packages/runtime-core/__tests__/components/KeepAlive.spec.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: ready to merge, scope: keep-alive, :cake: p2-nice-to-have

#11608 fix(types/computed): ensure type safety for `WritableComputedRef`
  packages-private/dts-test/ref.test-d.ts
  packages/reactivity/src/computed.ts
  packages/runtime-core/src/apiComputed.ts
Labels: ready to merge, scope: types

#11609 fix(types): update examples in JSDoc for augmenting global properties and custom options
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: ready to merge, :broom: p1-chore, easy for merge

#11581 fix(compiler-sfc): handle keyof operator with indexed object
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: :lady_beetle: bug, scope: sfc, ready for review

#11630 chore: add 3.4.38 changelog
  CHANGELOG.md
  changelogs/CHANGELOG-3.4.md
Labels: ready to merge, :broom: p1-chore, easy to merge

#11631 feat(workflows): auto close issues with `can't reproduce` label
  .github/workflows/close-cant-reproduce-issues.yml
Labels: ready for review

#11632 docs: modify email link error
  SECURITY.md
Labels: ready to merge, :broom: p1-chore, easy to merge

#11626 fix(runtime): handle errors for computed watch keys (fix #11624)
  packages/runtime-core/__tests__/errorHandling.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: :lady_beetle: bug, ready to merge

#10652 fix(runtime-core): ensure suspense content inherit scopeId
  packages/runtime-core/__tests__/scopeId.spec.ts
  packages/runtime-core/src/renderer.ts
Labels: scope: suspense, ready for review

#7247 fix(ssr): apply ssr props to the the fallback vnode-based branch in ssr
  packages/server-renderer/__tests__/ssrDynamicComponent.spec.ts
  packages/server-renderer/src/render.ts
Labels: ready to merge, scope: slots, scope: ssr, :hammer: p3-minor-bug

#5985 perf( runtime-core): use `apply` to avoid spreading.
  packages/runtime-core/src/compat/global.ts
  packages/runtime-core/src/compat/instanceEventEmitter.ts
Labels: ready to merge, :broom: p1-chore, easy to merge

#9998 types(runtime-core): optimizing type inference with defaults
  packages-private/dts-test/setupHelpers.test-d.ts
  packages/runtime-core/src/apiSetupHelpers.ts
Labels: ready to merge, scope: types

#9927 feat(reactivity): base `watch`, `getCurrentWatcher`, and `onWatcherCleanup`
  packages/reactivity/__tests__/watch.spec.ts
  packages/reactivity/src/index.ts
  packages/reactivity/src/watch.ts
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
  packages/runtime-core/src/componentOptions.ts
  packages/runtime-core/src/directives.ts
  packages/runtime-core/src/errorHandling.ts
  packages/runtime-core/src/index.ts
Labels: version: minor

#11663 chore: fix typo
  CHANGELOG.md
Labels: ready to merge, :broom: p1-chore, easy to merge

#11715 chore: correct the issue number
  packages/runtime-core/src/apiDefineComponent.ts
Labels: ready to merge, :broom: p1-chore, easy to merge

#11723 chore: improve error message for missing template and script tag in vue file
  packages/compiler-sfc/src/parse.ts
Labels: ready to merge, scope: compiler, :broom: p1-chore, easy to merge

#11668 fix(build): update paths for private packages in `dev` script
  package.json
  scripts/dev.js
Labels: ready to merge, easy to merge

#11721 chore(reactivity): effectScope.ts variable declarations optimized and remove useless code in effect.ts
  packages/reactivity/src/effect.ts
  packages/reactivity/src/effectScope.ts
Labels: ready to merge, :broom: p1-chore

#11718 fix(runtime-core): reset keep alive flag when the component is removed from include
  packages/runtime-core/__tests__/components/KeepAlive.spec.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: ready to merge, scope: keep-alive, :hammer: p3-minor-bug

#11680 fix(compiler-sfc): skip circular tsconfig project reference (#11382)
  packages/compiler-sfc/__tests__/compileScript/resolveType.spec.ts
  packages/compiler-sfc/src/script/resolveType.ts
Labels: :lady_beetle: bug, scope: sfc, ready for review

#6376 fix(reactivity): ref directly wrapped in proxy, should not track internal _value access. (fix: #6358)
  packages/reactivity/__tests__/ref.spec.ts
Labels: scope: reactivity, 🛑 on hold

#11655 fix(customElement): support set key on ceVNode
  packages/runtime-dom/src/apiCustomElement.ts
  packages/vue/__tests__/e2e/ssr-custom-element.html
  packages/vue/__tests__/e2e/ssr-custom-element.spec.ts
Labels: :lady_beetle: bug, scope: ssr, scope: custom elements, ready for review
