Repository vuejs/core, pull requests merged in 2024-05, with the labels that each got.

#10869 fix(shared): ensure invokeArrayFns handles undefined arguments
  packages/runtime-core/__tests__/apiLifecycle.spec.ts
  packages/shared/src/general.ts
Labels: ready to merge, 🔩 p2-edge-case

#10938 fix: correct the type of `<details>`'s `onToggle` event handler
  packages/runtime-dom/src/jsx.ts
Labels: ready to merge, scope: types

#10915 test: update coverage exclude
  vitest.config.ts
Labels: :broom: p1-chore

#10985 ci: fix RCE vulnerability in file overwrite
  .github/workflows/size-report.yml
Labels: security, :fire: p5-urgent

#10613 fix(custom-element): disconnect MutationObserver in nextTick in case that custom elements are moved
  packages/runtime-dom/__tests__/customElement.spec.ts
  packages/runtime-dom/src/apiCustomElement.ts
Labels: ready to merge, scope: custom elements

#10912 fix(KeepAlive): properly cache nested Suspense subtree
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: :lady_beetle: bug, ready to merge, scope: keep-alive, scope: suspense

#11005 chore: correct the comments in KeepAlive.ts
  packages/runtime-core/src/components/KeepAlive.ts
Labels: :broom: p1-chore

#7216 fix(ssr): fix hydration for node with empty text node
  packages/runtime-core/__tests__/hydration.spec.ts
  packages/runtime-core/src/hydration.ts
Labels: scope: ssr

#8731 refactor(runtime-core): prevent users from manually calling lifecycle hook function
  packages/runtime-core/src/apiLifecycle.ts
Labels: ready to merge

#8988 refactor: replace `Object.assign` with `extend`
  packages/runtime-core/src/componentPublicInstance.ts
Labels: ready to merge

#9069 feat(compiler-core): support Symbol in template
  packages/shared/src/globalsAllowList.ts
Labels: need test, scope: compiler

#9095 chore: improve readonly/reactive warning message
  packages/reactivity/src/reactive.ts
Labels: :cake: p2-nice-to-have

#9453 refactor(compiler-sfc): defineOptions avoid redundant conditional judgments
  packages/compiler-sfc/src/script/defineOptions.ts
Labels: :broom: p1-chore

#10263 dx(runtime-core): log the component object when warning about missing template/render function
  packages/runtime-core/src/component.ts
Labels: :cake: p2-nice-to-have

#9371 types(runtime-core): add `OnCleanup` parameter type in `this.$watch`
  packages/dts-test/watch.test-d.ts
  packages/runtime-core/src/apiWatch.ts
  packages/runtime-core/src/componentPublicInstance.ts
Labels: ready to merge, scope: reactivity, scope: types, :broom: p1-chore

#10891 fix(compiler-core): should set `<math>` tag as block to retain MathML namespace after patching
  packages/compiler-core/__tests__/transforms/transformElement.spec.ts
  packages/compiler-core/src/transforms/hoistStatic.ts
  packages/compiler-core/src/transforms/transformElement.ts
  packages/runtime-dom/__tests__/nodeOps.spec.ts
Labels: :lady_beetle: bug, ready to merge, :hammer: p3-minor-bug

#10919 chore: disallow optional chaining
  eslint.config.js
  packages/compiler-core/src/babelUtils.ts
  packages/reactivity/src/effect.ts
  packages/runtime-core/src/devtools.ts
  packages/runtime-core/src/hydration.ts
  packages/runtime-core/src/warning.ts
Labels: :broom: p1-chore

#9818 fix(teleport): not throw warning when teleport is disabled
  packages/runtime-core/src/components/Teleport.ts
Labels: scope: teleport

#11033 ci: omit pr number
  .github/workflows/size-data.yml
  .github/workflows/size-report.yml
Labels: scope: infra

#10969 fix(watch): deep watching symbol properties
  packages/runtime-core/__tests__/apiWatch.spec.ts
  packages/runtime-core/src/apiWatch.ts
Labels: scope: reactivity

#5821 fix(compiler-core): missing source and have with multiple spaces should emit error during compiler
  packages/compiler-core/__tests__/transforms/vFor.spec.ts
  packages/compiler-core/src/utils.ts
Labels: ready for review

#6100 fix(server-renderer): fix the bug that multi slot scope id does not work on component
  packages/server-renderer/__tests__/ssrScopeId.spec.ts
  packages/server-renderer/src/render.ts
Labels: scope: slots, scope: ssr, :hammer: p3-minor-bug, ready for review

#6765 fix(compiler-core): allow unicode to appear in simple identifiers
  packages/compiler-core/__tests__/transforms/vOn.spec.ts
  packages/compiler-core/src/utils.ts
Labels: ready to merge, :hammer: p3-minor-bug, ready for review

#11040 chore: fix typo (DistrubuteRef -> DistributeRef)
  packages/reactivity/src/ref.ts
Labels: :broom: p1-chore

#10367 chore(reactivity): change literal flag properties to enum flag properties
  packages/reactivity/src/computed.ts
  packages/reactivity/src/constants.ts
  packages/reactivity/src/ref.ts
  packages/shared/src/toDisplayString.ts
Labels: ready to merge, version: minor, :broom: p1-chore

#9129 types: improve readability of built-in type
  packages/reactivity/src/reactive.ts
  packages/reactivity/src/ref.ts
  packages/runtime-core/src/compat/instance.ts
Labels: ready to merge

#6936 fix(hmr): avoid infinite recursion when reloading hmr components (#6930)
  packages/runtime-core/__tests__/hmr.spec.ts
  packages/runtime-core/src/hmr.ts
Labels: :hammer: p3-minor-bug, ready for review

#7781 fix(compat): ensure proper handling of render function from SFC using Vue.extend (fix: #7766)
  packages/runtime-core/src/compat/component.ts
Labels: :hammer: p3-minor-bug, scope: v2 compat, ready for review

#7689 fix(runtime-core): ensure suspense creates dep's setupEffect with correct optimized flag (fix #7688)
  packages/runtime-core/src/components/Suspense.ts
  packages/runtime-core/src/renderer.ts
Labels: need guidance, scope: suspense, :hammer: p3-minor-bug
