Repository vuejs/core, pull requests merged in 2024-02, with the labels that each got.

#10218 fix: support v-bind shorthand syntax for slotName
  packages/compiler-core/__tests__/transforms/transformSlotOutlet.spec.ts
  packages/compiler-core/src/transforms/transformSlotOutlet.ts
Labels: scope: compiler, 🔩 p2-edge-case

#10315 chore(errorHandling): directly return value in callWithErrorHandling
  packages/runtime-core/src/errorHandling.ts
Labels: ready to merge

#10184 fix(suspense): handle suspense switching with nested suspense
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/Suspense.ts
Labels: :exclamation: p4-important, ready for review

#10378 chore(runtime-core): optimize validateComponentName
  packages/runtime-core/src/apiCreateApp.ts
  packages/runtime-core/src/component.ts
Labels: :broom: p1-chore

#10373 fix: should clear previous css string value
  packages/runtime-dom/__tests__/patchStyle.spec.ts
  packages/runtime-dom/src/modules/style.ts
Labels: 🔩 p2-edge-case

#10350 chore(reactivity): consistent variable naming
  packages/reactivity/src/baseHandlers.ts
Labels: :broom: p1-chore

#10417 fix(suspense): ensure nested suspense patching if in fallback state
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/Suspense.ts
Labels: scope: suspense, :hammer: p3-minor-bug

#10414 fix(warning): stringify args in warn handler
  packages/runtime-core/src/warning.ts
Labels: :hammer: p3-minor-bug, ready for review

#10416 fix(runtime-dom): avoid unset option's value
  packages/runtime-dom/__tests__/patchProps.spec.ts
  packages/runtime-dom/src/modules/props.ts
Labels: :exclamation: p4-important, ready for review
