Repository vuejs/core, pull requests merged in 2024-01, with the labels that each got.

#9966 fix(runtime-core): correctly assign suspenseId to avoid conflicts with the default id
  packages/runtime-core/__tests__/components/Suspense.spec.ts
  packages/runtime-core/src/components/Suspense.ts
  packages/sfc-playground/src/App.vue
Labels: need test

#9989 chore(runtime-core): remove console comment
  packages/runtime-core/src/scheduler.ts
Labels: ready to merge

#9999 fix(Suspense): correctly update the transition anchor point
  packages/runtime-core/src/components/Suspense.ts
  packages/vue/__tests__/e2e/Transition.spec.ts
Labels: scope: transition, scope: suspense, regression

#10034 fix(parser): skip compat mode check for SFC root `<template>` tags
  packages/compiler-core/src/parser.ts
Labels: scope: sfc, scope: v2 compat, regression

#9938 chore: use NOOP.
  packages/compiler-core/src/transform.ts
  packages/server-renderer/src/render.ts
Labels: :broom: p1-chore

#9984 refactor(runtime-core): use currentRenderingInstance direct.
  packages/runtime-core/src/directives.ts
Labels: :broom: p1-chore
