Repository vuejs/core, pull requests merged in 2025-03, with the labels that each got.

#13003 test(reactivity): enable tests marked as todo
  packages/reactivity/__tests__/gc.spec.ts
Labels: scope: reactivity, easy to merge

#12613 chore: update node v22 on netlify
  netlify.toml
Labels: ready to merge, :broom: p1-chore

#12645 feat(types): add type TemplateRef
  packages-private/dts-test/ref.test-d.ts
  packages/runtime-core/src/helpers/useTemplateRef.ts
  packages/runtime-core/src/index.ts
Labels: ready to merge, scope: types, :broom: p1-chore

#13043 fix(compiler): fix spelling error in domTagConfig
  scripts/verify-treeshaking.js
Labels: :broom: p1-chore

#12605 fix(types): the directive's modifiers should be optional
  packages-private/dts-test/appDirective.test-d.ts
  packages-private/dts-test/directives.test-d.ts
  packages/runtime-core/src/directives.ts
Labels: ready to merge, scope: types, :hammer: p3-minor-bug

#13063 types: enhance plugin type inference for better IDE support
  packages-private/dts-test/appUse.test-d.ts
  packages/runtime-core/src/apiCreateApp.ts
Labels: ready to merge, scope: types

#13074 chore(sfc-playground): dynamically set Vue version in downloaded project
  packages-private/sfc-playground/src/download/download.ts
  packages-private/sfc-playground/src/download/template/package.json
Labels: ready to merge, scope: playground

#13001 fix: always treat autocorrect as attribute
  packages/runtime-dom/src/patchProp.ts
Labels: ready to merge, browser specific, :cake: p2-nice-to-have

#13078 fix(reactivity): queuing effects in an array
  packages/reactivity/src/computed.ts
  packages/reactivity/src/system.ts
Labels: ready to merge, scope: reactivity, version: minor
